export const impactStats = [
  { value: '75,000+', label: 'Families Supported', labelAr: 'الأسر المدعومة' },
  { value: '30+', label: 'Countries Reached', labelAr: 'الدول المخدومة' },
  { value: '2,500+', label: 'Volunteers Active', labelAr: 'المتطوعون النشطون' },
  { value: '50+', label: 'Programs Running', labelAr: 'البرامج الفعّالة' },
];

export const programs = [
  {
    id: 1,
    slug: 'gaza-aid',
    name: 'For Our People in Gaza',
    nameAr: 'لأهلنا في غزة',
    description: 'Providing immediate humanitarian assistance to families affected by the crisis in Gaza',
    descriptionAr: 'توفير المساعدة الإنسانية الفورية للأسر المتضررة من الأزمة في غزة',
    longDescription: 'JHCO continues to provide humanitarian aid and support to families in Gaza affected by ongoing crisis. Our programs focus on emergency relief, medical assistance, and essential supplies to ensure human dignity.',
    longDescriptionAr: 'تواصل الهيئة تقديم المساعدات الإنسانية والدعم للأسر في غزة المتضررة من الأزمة المستمرة. تركز برامجنا على الإغاثة الطارئة والمساعدة الطبية والإمدادات الأساسية لضمان الكرامة الإنسانية.',
    category: 'Crisis Response',
    categoryAr: 'الاستجابة للأزمات',
    impact: '15,000+ families supported',
    impactAr: '15,000+ أسرة مدعومة',
    status: 'Active',
    objectives: ['Emergency relief provision', 'Medical assistance', 'Food security', 'Shelter support'],
    objectivesAr: ['توفير الإغاثة الطارئة', 'المساعدة الطبية', 'الأمن الغذائي', 'دعم المأوى'],
  },
  {
    id: 2,
    slug: 'amputees-gaza',
    name: 'Restoring Hope — Supporting Amputees in Gaza',
    nameAr: 'استعادة الأمل — دعم البتر في غزة',
    description: 'Prosthetic limbs, rehabilitation, and psychological support for amputees',
    descriptionAr: 'أطراف صناعية وإعادة تأهيل ودعم نفسي للبتر',
    longDescription: 'Specialized program providing prosthetic limbs, physical therapy, and psychological counseling to amputees in Gaza, restoring hope and enabling their return to productive lives.',
    longDescriptionAr: 'برنامج متخصص يوفر أطراف صناعية وعلاج فيزيائي واستشارات نفسية للبتر في غزة، مستعيداً الأمل وتمكين عودتهم للحياة المنتجة.',
    category: 'Healthcare',
    categoryAr: 'الرعاية الصحية',
    impact: '850+ amputees supported',
    impactAr: '850+ بتر مدعوم',
    status: 'Active',
    objectives: ['Prosthetic fitting', 'Physical rehabilitation', 'Mental health support', 'Social reintegration'],
    objectivesAr: ['تركيب أطراف صناعية', 'إعادة تأهيل بدني', 'دعم الصحة النفسية', 'إعادة الدمج الاجتماعي'],
  },
  {
    id: 3,
    slug: 'clothing-bank',
    name: 'Clothing Bank Initiative',
    nameAr: 'مبادرة بنك الملابس',
    description: 'Providing quality clothing to families in need across multiple regions',
    descriptionAr: 'توفير الملابس عالية الجودة للأسر المحتاجة عبر عدة مناطق',
    longDescription: 'Collecting and distributing quality clothing to vulnerable families, ensuring dignity and basic needs are met during challenging times.',
    longDescriptionAr: 'جمع وتوزيع الملابس عالية الجودة على الأسر الضعيفة، مما يضمن الكرامة وتلبية الاحتياجات الأساسية أثناء الأوقات الصعبة.',
    category: 'Basic Needs',
    categoryAr: 'الاحتياجات الأساسية',
    impact: '25,000+ people clothed',
    impactAr: '25,000+ شخص مُكسى',
    status: 'Active',
    objectives: ['Clothing collection', 'Distribution', 'Hygiene support', 'Dignity restoration'],
    objectivesAr: ['جمع الملابس', 'التوزيع', 'دعم النظافة', 'استعادة الكرامة'],
  },
  {
    id: 4,
    slug: 'education',
    name: 'Educational Support Program',
    nameAr: 'برنامج الدعم التعليمي',
    description: 'Scholarships and educational resources for underprivileged students',
    descriptionAr: 'منح وموارد تعليمية للطلاب المحرومين',
    longDescription: 'Providing scholarships, educational materials, and tutoring support to ensure every child has access to quality education regardless of economic circumstances.',
    longDescriptionAr: 'توفير المنح والمواد التعليمية ودعم الدروس الخصوصية لضمان حصول كل طفل على تعليم عالي الجودة بغض النظر عن الظروف الاقتصادية.',
    category: 'Education',
    categoryAr: 'التعليم',
    impact: '8,500+ students empowered',
    impactAr: '8,500+ طالب مُمكّن',
    status: 'Active',
    objectives: ['Scholarship provision', 'Learning materials', 'Tutoring support', 'School enrollment'],
    objectivesAr: ['توفير المنح', 'مواد التعلم', 'دعم الدروس', 'التحاق المدارس'],
  },
  {
    id: 5,
    slug: 'healthcare',
    name: 'Medical Clinics Network',
    nameAr: 'شبكة العيادات الطبية',
    description: 'Free healthcare services including checkups, medications, and surgeries',
    descriptionAr: 'خدمات طبية مجانية تشمل الفحوصات والأدوية والعمليات الجراحية',
    longDescription: 'Operating medical clinics across regions providing free healthcare services to ensure vulnerable populations have access to essential medical care.',
    longDescriptionAr: 'تشغيل عيادات طبية عبر المناطق توفير خدمات طبية مجانية لضمان حصول السكان الضعفاء على الرعاية الطبية الأساسية.',
    category: 'Healthcare',
    categoryAr: 'الرعاية الصحية',
    impact: '12,000+ treated annually',
    impactAr: '12,000+ مريض سنوياً',
    status: 'Active',
    objectives: ['Medical checkups', 'Medication provision', 'Surgical support', 'Health education'],
    objectivesAr: ['الفحوصات الطبية', 'توفير الأدوية', 'الدعم الجراحي', 'التثقيف الصحي'],
  },
  {
    id: 6,
    slug: 'livelihoods',
    name: 'Livelihood and Skills Training',
    nameAr: 'التدريب على سبل العيش والمهارات',
    description: 'Vocational training and income-generating activities for economic empowerment',
    descriptionAr: 'التدريب المهني والأنشطة المدرة للدخل للتمكين الاقتصادي',
    longDescription: 'Equipping individuals with vocational skills and supporting income-generating activities to achieve economic independence and sustainable livelihoods.',
    longDescriptionAr: 'تجهيز الأفراد بالمهارات المهنية ودعم الأنشطة المدرة للدخل لتحقيق الاستقلالية الاقتصادية وسبل العيش المستدامة.',
    category: 'Economic Empowerment',
    categoryAr: 'التمكين الاقتصادي',
    impact: '3,200+ trained',
    impactAr: '3,200+ مُدرّب',
    status: 'Active',
    objectives: ['Skills training', 'Job placement', 'Microfinance support', 'Business development'],
    objectivesAr: ['تدريب المهارات', 'التوظيف', 'دعم التمويل الأصغر', 'تطوير الأعمال'],
  },
];

export const news = [
  {
    id: 1,
    slug: 'lebanon-aid-convoy',
    title: 'Jordan Dispatches Ninth Humanitarian Aid Convoy to Lebanon',
    titleAr: 'الأردن يرسل قافلة الإغاثة الإنسانية التاسعة إلى لبنان',
    excerpt: 'JHCO continues supporting Lebanon with a ninth humanitarian relief convoy',
    excerptAr: 'تواصل الهيئة دعم لبنان مع قافلة الإغاثة الإنسانية التاسعة',
    date: new Date('2026-06-25'),
    category: 'Crisis Response',
    categoryAr: 'الاستجابة للأزمات',
  },
  {
    id: 2,
    slug: 'bahrain-cooperation',
    title: 'JHCO and the Bahrain Royal Charity Organisation Sign Cooperation Agreement for Gaza',
    titleAr: 'الهيئة والمؤسسة الملكية للأعمال الخيرية توقعان اتفاقية تعاون لغزة',
    excerpt: 'A new agreement to support those affected in the Gaza Strip',
    excerptAr: 'اتفاق جديد لدعم المتضررين في قطاع غزة',
    date: new Date('2026-06-25'),
    category: 'Partnerships',
    categoryAr: 'الشراكات',
  },
  {
    id: 3,
    slug: 'education-initiative',
    title: 'Educational Support Program Reaches 8,500 Students',
    titleAr: 'برنامج الدعم التعليمي يصل إلى 8,500 طالب',
    excerpt: 'Celebrating milestone achievement in educational empowerment',
    excerptAr: 'الاحتفال بمرحلة فاصلة في التمكين التعليمي',
    date: new Date('2026-06-20'),
    category: 'Education',
    categoryAr: 'التعليم',
  },
];
