export const impactStats = [
  { value: '75,000+', label: 'Families Supported', labelAr: 'الأسر المدعومة' },
  { value: '30+', label: 'Countries Reached', labelAr: 'الدول المخدومة' },
  { value: '2,500+', label: 'Volunteers Active', labelAr: 'المتطوعون النشطون' },
  { value: '50+', label: 'Programs Running', labelAr: 'البرامج الفعّالة' },
];

export const royalInitiatives = [
  {
    id: 1,
    slug: 'bahrain-gaza-partnership',
    name: 'Bahrain Royal Charity Organisation Partnership - Gaza',
    nameAr: 'شراكة مؤسسة البحرين الملكية للأعمال الخيرية - غزة',
    description: 'Joint humanitarian initiative with Bahrain Royal Charity Organisation providing emergency relief to Gaza',
    descriptionAr: 'مبادرة إنسانية مشتركة مع مؤسسة البحرين الملكية للأعمال الخيرية توفر الإغاثة الطارئة إلى غزة',
    longDescription: 'A landmark cooperation agreement signed between JHCO and the Bahrain Royal Charity Organisation to provide comprehensive humanitarian assistance to families affected by the crisis in Gaza, including emergency relief, medical aid, food security, and shelter support.',
    longDescriptionAr: 'اتفاقية تعاون تاريخية وقعتها الهيئة ومؤسسة البحرين الملكية للأعمال الخيرية لتقديم مساعدة إنسانية شاملة للأسر المتضررة من الأزمة في غزة، تشمل الإغاثة الطارئة والمساعدة الطبية والأمن الغذائي ودعم المأوى.',
    category: 'Royal Partnerships',
    categoryAr: 'الشراكات الملكية',
    impact: '20,000+ families supported',
    impactAr: '20,000+ أسرة مدعومة',
    status: 'Active',
    partner: 'Bahrain Royal Charity Organisation',
    partnerAr: 'مؤسسة البحرين الملكية للأعمال الخيرية',
    objectives: ['Emergency relief provision', 'Medical assistance', 'Food security', 'Shelter support', 'Rehabilitation services'],
    objectivesAr: ['توفير الإغاثة الطارئة', 'المساعدة الطبية', 'الأمن الغذائي', 'دعم المأوى', 'خدمات إعادة التأهيل'],
  },
  {
    id: 2,
    slug: 'royal-education-initiative',
    name: 'Royal Education Enhancement Program',
    nameAr: 'برنامج تعزيز التعليم الملكي',
    description: 'Premium educational scholarship program funded by royal patronage across multiple regions',
    descriptionAr: 'برنامج منح دراسية متميز ممول برعاية ملكية عبر عدة مناطق',
    longDescription: 'A prestigious educational initiative providing premium scholarships, advanced learning materials, and mentorship programs to exceptional students from underprivileged backgrounds, supported by royal patronage and institutional grants.',
    longDescriptionAr: 'مبادرة تعليمية مرموقة توفر منح دراسية متميزة ومواد تعليمية متقدمة وبرامج إرشادية للطلاب المتفوقين من خلفيات محرومة، مدعومة برعاية ملكية ومنح مؤسسية.',
    category: 'Royal Education',
    categoryAr: 'التعليم الملكي',
    impact: '5,200+ students empowered',
    impactAr: '5,200+ طالب مُمكّن',
    status: 'Active',
    partner: 'Royal Education Foundation',
    partnerAr: 'مؤسسة التعليم الملكية',
    objectives: ['Scholarship distribution', 'Mentorship programs', 'Advanced learning materials', 'Capacity building', 'International exchange'],
    objectivesAr: ['توزيع المنح', 'برامج الإرشاد', 'مواد التعليم المتقدمة', 'بناء القدرات', 'التبادل الدولي'],
  },
  {
    id: 3,
    slug: 'royal-healthcare-excellence',
    name: 'Royal Healthcare Excellence Initiative',
    nameAr: 'مبادرة التميز الصحي الملكي',
    description: 'State-of-the-art medical facilities and specialist services supported by royal patronage',
    descriptionAr: 'منشآت طبية متقدمة وخدمات متخصصة مدعومة برعاية ملكية',
    longDescription: 'A comprehensive healthcare initiative establishing specialized medical centers and clinics with advanced equipment, specialist doctors, and comprehensive treatment programs for underserved populations, backed by royal patronage and institutional support.',
    longDescriptionAr: 'مبادرة صحية شاملة تنشئ مراكز طبية متخصصة وعيادات بمعدات متقدمة وأطباء متخصصين وبرامج علاج شاملة للسكان غير المخدومين، مدعومة برعاية ملكية ودعم مؤسسي.',
    category: 'Royal Healthcare',
    categoryAr: 'الرعاية الصحية الملكية',
    impact: '18,000+ treated annually',
    impactAr: '18,000+ مريض سنوياً',
    status: 'Active',
    partner: 'Royal Medical Authority',
    partnerAr: 'الهيئة الطبية الملكية',
    objectives: ['Specialized medical centers', 'Advanced diagnostics', 'Surgical services', 'Specialist consultation', 'Medical research'],
    objectivesAr: ['مراكز طبية متخصصة', 'التشخيص المتقدم', 'الخدمات الجراحية', 'الاستشارة المتخصصة', 'البحث الطبي'],
  },
  {
    id: 4,
    slug: 'royal-women-empowerment',
    name: 'Royal Women Empowerment & Leadership Program',
    nameAr: 'برنامج تمكين النساء والقيادة الملكي',
    description: 'Empowerment and leadership development for women under royal patronage',
    descriptionAr: 'التمكين وتطوير القيادة للنساء تحت الرعاية الملكية',
    longDescription: 'A prestigious program providing comprehensive training, business development support, and leadership development to women from disadvantaged communities, enabling economic independence and social leadership under royal patronage.',
    longDescriptionAr: 'برنامج مرموق يوفر تدريباً شاملاً ودعماً لتطوير الأعمال وتطوير القيادة للنساء من المجتمعات المحرومة، يمكنهن من الاستقلال الاقتصادي والقيادة الاجتماعية تحت الرعاية الملكية.',
    category: 'Royal Empowerment',
    categoryAr: 'التمكين الملكي',
    impact: '3,500+ women empowered',
    impactAr: '3,500+ امرأة مُمكّنة',
    status: 'Active',
    partner: 'Royal Women Foundation',
    partnerAr: 'مؤسسة النساء الملكية',
    objectives: ['Business training', 'Microfinance access', 'Leadership development', 'Mentorship', 'Market access support'],
    objectivesAr: ['تدريب الأعمال', 'الوصول إلى التمويل الأصغر', 'تطوير القيادة', 'الإرشاد', 'دعم الوصول إلى السوق'],
  },
  {
    id: 5,
    slug: 'royal-youth-development',
    name: 'Royal Youth Development & Skills Initiative',
    nameAr: 'مبادرة تطوير الشباب والمهارات الملكية',
    description: 'Comprehensive youth development program combining skills training, mentorship, and career placement',
    descriptionAr: 'برنامج تطوير شباب شامل يجمع بين تدريب المهارات والإرشاد والتوظيف',
    longDescription: 'A premier youth development initiative providing comprehensive vocational training, internship opportunities, mentorship from industry leaders, and career placement assistance to young people, supported by royal patronage and institutional partnerships.',
    longDescriptionAr: 'مبادرة تطوير شباب برتبة عالية توفر تدريباً مهنياً شاملاً وفرص تدريب داخلي وإرشاداً من قادة الصناعة والمساعدة على التوظيف، مدعومة برعاية ملكية وشراكات مؤسسية.',
    category: 'Royal Youth Programs',
    categoryAr: 'برامج الشباب الملكية',
    impact: '7,800+ youth trained',
    impactAr: '7,800+ شاب مُدرّب',
    status: 'Active',
    partner: 'Royal Youth Foundation',
    partnerAr: 'مؤسسة الشباب الملكية',
    objectives: ['Vocational training', 'Internship placement', 'Mentorship programs', 'Career counseling', 'Job placement'],
    objectivesAr: ['التدريب المهني', 'توظيف التدريب الداخلي', 'برامج الإرشاد', 'الاستشارة الوظيفية', 'توظيف الوظائف'],
  },
];

export const programs = [
  {
    id: 1,
    slug: 'gaza-aid',
    name: 'For Our People in Gaza',
    nameAr: 'لأهلنا في غزة',
    description: 'Providing immediate humanitarian assistance to families affected by the crisis in Gaza',
    descriptionAr: 'توفير المساعدة الإنسانية الفورية للأسر المتضررة من الأزمة في غزة',
    longDescription: 'JHCO continues to provide humanitarian aid and support to families in Gaza affected by ongoing crisis. Our programs focus on emergency relief, medical assistance, and essential supplies to ensure human dignity.',
    longDescriptionAr: 'تواصل الهيئة تقديم المساعدات الإنسانية والدعم للأسر في غزة المتضررة من الأزمة المستمرة. تركز برامجنا على الإغاثة الطارئة والمساعدة الطبية والإمدادات الأساسية لضمان الكرامة الإنسانية.',
    category: 'Crisis Response',
    categoryAr: 'الاستجابة للأزمات',
    impact: '15,000+ families supported',
    impactAr: '15,000+ أسرة مدعومة',
    status: 'Active',
    objectives: ['Emergency relief provision', 'Medical assistance', 'Food security', 'Shelter support'],
    objectivesAr: ['توفير الإغاثة الطارئة', 'المساعدة الطبية', 'الأمن الغذائي', 'دعم المأوى'],
  },
  {
    id: 2,
    slug: 'amputees-gaza',
    name: 'Restoring Hope — Supporting Amputees in Gaza',
    nameAr: 'استعادة الأمل — دعم البتر في غزة',
    description: 'Prosthetic limbs, rehabilitation, and psychological support for amputees',
    descriptionAr: 'أطراف صناعية وإعادة تأهيل ودعم نفسي للبتر',
    longDescription: 'Specialized program providing prosthetic limbs, physical therapy, and psychological counseling to amputees in Gaza, restoring hope and enabling their return to productive lives.',
    longDescriptionAr: 'برنامج متخصص يوفر أطراف صناعية وعلاج فيزيائي واستشارات نفسية للبتر في غزة، مستعيداً الأمل وتمكين عودتهم للحياة المنتجة.',
    category: 'Healthcare',
    categoryAr: 'الرعاية الصحية',
    impact: '850+ amputees supported',
    impactAr: '850+ بتر مدعوم',
    status: 'Active',
    objectives: ['Prosthetic fitting', 'Physical rehabilitation', 'Mental health support', 'Social reintegration'],
    objectivesAr: ['تركيب أطراف صناعية', 'إعادة تأهيل بدني', 'دعم الصحة النفسية', 'إعادة الدمج الاجتماعي'],
  },
  {
    id: 3,
    slug: 'clothing-bank',
    name: 'Clothing Bank Initiative',
    nameAr: 'مبادرة بنك الملابس',
    description: 'Providing quality clothing to families in need across multiple regions',
    descriptionAr: 'توفير الملابس عالية الجودة للأسر المحتاجة عبر عدة مناطق',
    longDescription: 'Collecting and distributing quality clothing to vulnerable families, ensuring dignity and basic needs are met during challenging times.',
    longDescriptionAr: 'جمع وتوزيع الملابس عالية الجودة على الأسر الضعيفة، مما يضمن الكرامة وتلبية الاحتياجات الأساسية أثناء الأوقات الصعبة.',
    category: 'Basic Needs',
    categoryAr: 'الاحتياجات الأساسية',
    impact: '25,000+ people clothed',
    impactAr: '25,000+ شخص مُكسى',
    status: 'Active',
    objectives: ['Clothing collection', 'Distribution', 'Hygiene support', 'Dignity restoration'],
    objectivesAr: ['جمع الملابس', 'التوزيع', 'دعم النظافة', 'استعادة الكرامة'],
  },
  {
    id: 4,
    slug: 'education',
    name: 'Educational Support Program',
    nameAr: 'برنامج الدعم التعليمي',
    description: 'Scholarships and educational resources for underprivileged students',
    descriptionAr: 'منح وموارد تعليمية للطلاب المحرومين',
    longDescription: 'Providing scholarships, educational materials, and tutoring support to ensure every child has access to quality education regardless of economic circumstances.',
    longDescriptionAr: 'توفير المنح والمواد التعليمية ودعم الدروس الخصوصية لضمان حصول كل طفل على تعليم عالي الجودة بغض النظر عن الظروف الاقتصادية.',
    category: 'Education',
    categoryAr: 'التعليم',
    impact: '8,500+ students empowered',
    impactAr: '8,500+ طالب مُمكّن',
    status: 'Active',
    objectives: ['Scholarship provision', 'Learning materials', 'Tutoring support', 'School enrollment'],
    objectivesAr: ['توفير المنح', 'مواد التعلم', 'دعم الدروس', 'التحاق المدارس'],
  },
  {
    id: 5,
    slug: 'healthcare',
    name: 'Medical Clinics Network',
    nameAr: 'شبكة العيادات الطبية',
    description: 'Free healthcare services including checkups, medications, and surgeries',
    descriptionAr: 'خدمات طبية مجانية تشمل الفحوصات والأدوية والعمليات الجراحية',
    longDescription: 'Operating medical clinics across regions providing free healthcare services to ensure vulnerable populations have access to essential medical care.',
    longDescriptionAr: 'تشغيل عيادات طبية عبر المناطق توفير خدمات طبية مجانية لضمان حصول السكان الضعفاء على الرعاية الطبية الأساسية.',
    category: 'Healthcare',
    categoryAr: 'الرعاية الصحية',
    impact: '12,000+ treated annually',
    impactAr: '12,000+ مريض سنوياً',
    status: 'Active',
    objectives: ['Medical checkups', 'Medication provision', 'Surgical support', 'Health education'],
    objectivesAr: ['الفحوصات الطبية', 'توفير الأدوية', 'الدعم الجراحي', 'التثقيف الصحي'],
  },
  {
    id: 6,
    slug: 'livelihoods',
    name: 'Livelihood and Skills Training',
    nameAr: 'التدريب على سبل العيش والمهارات',
    description: 'Vocational training and income-generating activities for economic empowerment',
    descriptionAr: 'التدريب المهني والأنشطة المدرة للدخل للتمكين الاقتصادي',
    longDescription: 'Equipping individuals with vocational skills and supporting income-generating activities to achieve economic independence and sustainable livelihoods.',
    longDescriptionAr: 'تجهيز الأفراد بالمهارات المهنية ودعم الأنشطة المدرة للدخل لتحقيق الاستقلالية الاقتصادية وسبل العيش المستدامة.',
    category: 'Economic Empowerment',
    categoryAr: 'التمكين الاقتصادي',
    impact: '3,200+ trained',
    impactAr: '3,200+ مُدرّب',
    status: 'Active',
    objectives: ['Skills training', 'Job placement', 'Microfinance support', 'Business development'],
    objectivesAr: ['تدريب المهارات', 'التوظيف', 'دعم التمويل الأصغر', 'تطوير الأعمال'],
  },
  {
    id: 7,
    slug: 'food-security',
    name: 'Food Security Program',
    nameAr: 'برنامج الأمن الغذائي',
    description: 'Emergency food assistance and livelihood support ensuring nutritional dignity and sustainable food systems',
    descriptionAr: 'المساعدة الغذائية الطارئة ودعم سبل العيش لضمان الكرامة الغذائية والأنظمة الغذائية المستدامة',
    longDescription: 'The JHCO Food Security Program addresses hunger and malnutrition across vulnerable communities worldwide. We provide emergency food distribution, nutrition education, agricultural training, and livelihood support to build lasting food security. Our multi-faceted approach combines immediate relief with long-term sustainable solutions, empowering communities to achieve food independence.',
    longDescriptionAr: 'يعالج برنامج الأمن الغذائي بالهيئة الجوع وسوء التغذية عبر المجتمعات الضعيفة في جميع أنحاء العالم. نوفر توزيع الغذاء الطارئ والتثقيف الغذائي والتدريب الزراعي ودعم سبل العيش لبناء أمن غذائي دائم. يجمع نهجنا متعدد الأوجه بين الإغاثة الفورية والحلول المستدامة طويلة الأجل، مما يمكن المجتمعات من تحقيق الاستقلال الغذائي.',
    category: 'Food Security',
    categoryAr: 'الأمن الغذائي',
    impact: '125,000+ people served',
    impactAr: '125,000+ شخص مخدوم',
    status: 'Active',
    objectives: ['Emergency food distribution', 'Nutrition education', 'Agricultural training', 'Livelihood support', 'School feeding programs', 'Community sustainability'],
    objectivesAr: ['توزيع الغذاء الطارئ', 'التثقيف الغذائي', 'التدريب الزراعي', 'دعم سبل العيش', 'برامج التغذية المدرسية', 'استدامة المجتمع'],
  },
  {
    id: 8,
    slug: 'crisis-response-program',
    name: 'Crisis Response Program',
    nameAr: 'برنامج الاستجابة للأزمات',
    description: 'Comprehensive rapid-response initiatives providing humanitarian aid during emergencies and crises worldwide',
    descriptionAr: 'مبادرات استجابة سريعة شاملة توفر المساعدة الإنسانية أثناء الطوارئ والأزمات حول العالم',
    longDescription: 'JHCO\'s Crisis Response Program is a comprehensive, rapid-response initiative designed to provide immediate humanitarian assistance during emergencies and crises worldwide. We maintain constant readiness to deploy teams, resources, and expertise to affected regions within hours of a crisis occurrence. Our program integrates emergency relief distribution, medical support, shelter provision, and psychosocial assistance to address the multifaceted needs of affected populations. We work collaboratively with local partners and international organizations to maximize impact and ensure dignity in our response.',
    longDescriptionAr: 'برنامج الاستجابة للأزمات بالهيئة هو مبادرة استجابة سريعة شاملة مصممة لتوفير المساعدة الإنسانية الفورية أثناء الطوارئ والأزمات حول العالم. نحافظ على جاهزية مستمرة لنشر الفرق والموارد والخبرات للمناطق المتضررة في غضون ساعات من حدوث الأزمة. يدمج برنامجنا توزيع الإغاثة الطارئة والدعم الطبي وتوفير المأوى والمساعدة النفسية الاجتماعية لمعالجة الاحتياجات المتعددة الأوجه للسكان المتضررين. نعمل بشكل تعاوني مع الشركاء المحليين والمنظمات الدولية لتعظيم التأثير وضمان الكرامة في استجابتنا.',
    category: 'Crisis Response',
    categoryAr: 'الاستجابة للأزمات',
    impact: '150,000+ lives assisted',
    impactAr: '150,000+ حياة تم تقديم المساعدة لها',
    status: 'Active',
    objectives: [
      'Immediate emergency response deployment',
      'Food security and essential supplies distribution',
      'Medical assistance and healthcare services',
      'Shelter and temporary housing provision',
      'Psychosocial support and counseling',
      'Search and rescue operations',
      'Coordination with international humanitarian partners',
      'Post-crisis recovery and rehabilitation support'
    ],
    objectivesAr: [
      'نشر الاستجابة للطوارئ الفورية',
      'توزيع الأمن الغذائي والإمدادات الأساسية',
      'المساعدة الطبية وخدمات الرعاية الصحية',
      'توفير المأوى والإسكان المؤقت',
      'الدعم النفسي الاجتماعي والاستشارات',
      'عمليات البحث والإنقاذ',
      'التنسيق مع الشركاء الإنسانيين الدوليين',
      'دعم التعافي وإعادة التأهيل بعد الأزمة'
    ],
  },
];

export const news = [
  {
    id: 1,
    slug: 'lebanon-aid-convoy',
    title: 'Jordan Dispatches Ninth Humanitarian Aid Convoy to Lebanon',
    titleAr: 'الأردن يرسل قافلة الإغاثة الإنسانية التاسعة إلى لبنان',
    excerpt: 'JHCO continues supporting Lebanon with a ninth humanitarian relief convoy',
    excerptAr: 'تواصل الهيئة دعم لبنان مع قافلة الإغاثة الإنسانية التاسعة',
    date: new Date('2026-06-25'),
    category: 'Crisis Response',
    categoryAr: 'الاستجابة للأزمات',
  },
  {
    id: 2,
    slug: 'bahrain-cooperation',
    title: 'JHCO and the Bahrain Royal Charity Organisation Sign Cooperation Agreement for Gaza',
    titleAr: 'الهيئة والمؤسسة الملكية للأعمال الخيرية توقعان اتفاقية تعاون لغزة',
    excerpt: 'A new agreement to support those affected in the Gaza Strip',
    excerptAr: 'اتفاق جديد لدعم المتضررين في قطاع غزة',
    date: new Date('2026-06-25'),
    category: 'Partnerships',
    categoryAr: 'الشراكات',
  },
  {
    id: 3,
    slug: 'education-initiative',
    title: 'Educational Support Program Reaches 8,500 Students',
    titleAr: 'برنامج الدعم التعليمي يصل إلى 8,500 طالب',
    excerpt: 'Celebrating milestone achievement in educational empowerment',
    excerptAr: 'الاحتفال بمرحلة فاصلة في التمكين التعليمي',
    date: new Date('2026-06-20'),
    category: 'Education',
    categoryAr: 'التعليم',
  },
];

// Geographic Data - Regions and Countries
export const regions = [
  {
    id: 1,
    slug: 'asia',
    name: 'Asia',
    nameAr: 'آسيا',
    description: 'JHCO operates across 17 countries in Asia, providing humanitarian aid and development support to vulnerable populations across the continent.',
    descriptionAr: 'تعمل الهيئة عبر 17 دولة في آسيا، توفر المساعدات الإنسانية والدعم التنموي للفئات الضعيفة عبر القارة.',
    countries: ['afghanistan', 'bangladesh', 'china', 'georgia', 'indonesia', 'iran', 'iraq', 'japan', 'lebanon', 'palestine', 'pakistan', 'philippines', 'sri-lanka', 'syria', 'taiwan', 'thailand', 'turkey'],
  },
  {
    id: 2,
    slug: 'africa',
    name: 'Africa',
    nameAr: 'أفريقيا',
    description: 'JHCO supports 10 African nations with crisis response, healthcare, education, and livelihood programs to build sustainable development.',
    descriptionAr: 'تدعم الهيئة 10 دول أفريقية ببرامج الاستجابة للأزمات والرعاية الصحية والتعليم وسبل العيش لبناء تنمية مستدامة.',
    countries: ['algeria', 'comoros', 'congo', 'egypt', 'ivory-coast', 'liberia', 'libya', 'morocco', 'somalia', 'sudan'],
  },
  {
    id: 3,
    slug: 'europe',
    name: 'Europe',
    nameAr: 'أوروبا',
    description: 'JHCO operates in 7 European countries, focusing on crisis response and humanitarian assistance to vulnerable communities.',
    descriptionAr: 'تعمل الهيئة في 7 دول أوروبية، مركزة على الاستجابة للأزمات والمساعدة الإنسانية للمجتمعات الضعيفة.',
    countries: ['abkhazia', 'bosnia', 'bulgaria', 'chechnya', 'macedonia', 'romania', 'south-ossetia'],
  },
  {
    id: 4,
    slug: 'americas',
    name: 'Americas',
    nameAr: 'الأمريكتان',
    description: 'JHCO extends its humanitarian reach to the Americas, with special focus on emergency response and community development.',
    descriptionAr: 'تمد الهيئة نطاق عملها الإنساني ليشمل الأمريكتان، مع التركيز على الاستجابة للطوارئ وتنمية المجتمع.',
    countries: ['haiti'],
  },
];

export const countries = [
  // ASIA
  {
    id: 1,
    slug: 'afghanistan',
    name: 'Afghanistan',
    nameAr: 'أفغانستان',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇦🇫',
    programs: ['Healthcare', 'Education', 'Food Security', 'Livelihoods'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'الأمن الغذائي', 'سبل العيش'],
    impact: '12,000+ families supported',
    impactAr: '12,000+ أسرة مدعومة',
    description: 'JHCO operates medical clinics and educational programs across Afghanistan, providing essential healthcare and scholarship support to vulnerable communities.',
    descriptionAr: 'تعمل الهيئة على تشغيل عيادات طبية وبرامج تعليمية في أفغانستان، توفر الرعاية الصحية الأساسية والدعم المنح الدراسية للمجتمعات الضعيفة.',
    office: 'Kabul Regional Office',
    officeAr: 'مكتب كابول الإقليمي',
  },
  {
    id: 2,
    slug: 'bangladesh',
    name: 'Bangladesh',
    nameAr: 'بنغلاديش',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇧🇩',
    programs: ['Healthcare', 'Education', 'Livelihood Training', 'Women Empowerment'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش', 'تمكين النساء'],
    impact: '8,500+ individuals trained',
    impactAr: '8,500+ فرد مُدرّب',
    description: 'Active programs in healthcare delivery and vocational training, empowering women and youth in rural communities.',
    descriptionAr: 'برامج نشطة في توفير الرعاية الصحية والتدريب المهني، تمكين النساء والشباب في المجتمعات الريفية.',
    office: 'Dhaka Coordination Center',
    officeAr: 'مركز داكا التنسيقي',
  },
  {
    id: 3,
    slug: 'china',
    name: 'China',
    nameAr: 'الصين',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇨🇳',
    programs: ['Education', 'Healthcare'],
    programsAr: ['التعليم', 'الرعاية الصحية'],
    impact: '3,200+ students supported',
    impactAr: '3,200+ طالب مدعوم',
    description: 'Educational scholarships and healthcare initiatives supporting vulnerable populations in rural regions.',
    descriptionAr: 'منح دراسية ومبادرات الرعاية الصحية تدعم الفئات الضعيفة في المناطق الريفية.',
    office: 'Beijing Office',
    officeAr: 'مكتب بكين',
  },
  {
    id: 4,
    slug: 'georgia',
    name: 'Georgia',
    nameAr: 'جورجيا',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇬🇪',
    programs: ['Crisis Response', 'Healthcare', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي'],
    impact: '6,500+ crisis-affected supported',
    impactAr: '6,500+ متضرر من الأزمات مدعوم',
    description: 'Emergency humanitarian assistance to conflict-affected communities, including food distribution and medical support.',
    descriptionAr: 'مساعدة إنسانية طارئة للمجتمعات المتأثرة بالصراعات، بما فيها توزيع الغذاء والدعم الطبي.',
    office: 'Tbilisi Humanitarian Hub',
    officeAr: 'مركز تبليسي الإنساني',
  },
  {
    id: 5,
    slug: 'indonesia',
    name: 'Indonesia',
    nameAr: 'إندونيسيا',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇮🇩',
    programs: ['Disaster Relief', 'Healthcare', 'Education'],
    programsAr: ['إغاثة الكوارث', 'الرعاية الصحية', 'التعليم'],
    impact: '45,000+ disaster-affected supported',
    impactAr: '45,000+ متضرر من الكوارث مدعوم',
    description: 'Disaster response operations and ongoing health and education programs for vulnerable communities.',
    descriptionAr: 'عمليات الاستجابة للكوارث وبرامج الصحة والتعليم المستمرة للمجتمعات الضعيفة.',
    office: 'Jakarta Emergency Operations',
    officeAr: 'عمليات جاكرتا الطارئة',
  },
  {
    id: 6,
    slug: 'iran',
    name: 'Iran',
    nameAr: 'إيران',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇮🇷',
    programs: ['Healthcare', 'Livelihood Support'],
    programsAr: ['الرعاية الصحية', 'دعم سبل العيش'],
    impact: '5,200+ individuals served',
    impactAr: '5,200+ فرد مخدوم',
    description: 'Medical clinics and economic empowerment initiatives supporting vulnerable populations.',
    descriptionAr: 'عيادات طبية ومبادرات التمكين الاقتصادي تدعم الفئات الضعيفة.',
    office: 'Tehran Operations Office',
    officeAr: 'مكتب طهران التشغيلي',
  },
  {
    id: 7,
    slug: 'iraq',
    name: 'Iraq',
    nameAr: 'العراق',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇮🇶',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم'],
    impact: '28,000+ crisis-affected supported',
    impactAr: '28,000+ متضرر من الأزمات مدعوم',
    description: 'Comprehensive humanitarian response including emergency aid, medical support, food distribution, and educational programs.',
    descriptionAr: 'استجابة إنسانية شاملة تشمل المساعدات الطارئة والدعم الطبي وتوزيع الغذاء والبرامج التعليمية.',
    office: 'Baghdad Central Hub',
    officeAr: 'مركز بغداد المركزي',
  },
  {
    id: 8,
    slug: 'japan',
    name: 'Japan',
    nameAr: 'اليابان',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇯🇵',
    programs: ['Education', 'Community Support'],
    programsAr: ['التعليم', 'دعم المجتمع'],
    impact: '2,500+ beneficiaries',
    impactAr: '2,500+ مستفيد',
    description: 'Educational programs and community development initiatives supporting international cooperation.',
    descriptionAr: 'برامج تعليمية ومبادرات تنمية المجتمع تدعم التعاون الدولي.',
    office: 'Tokyo Coordination Office',
    officeAr: 'مكتب طوكيو التنسيقي',
  },
  {
    id: 9,
    slug: 'lebanon',
    name: 'Lebanon',
    nameAr: 'لبنان',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇱🇧',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education', 'Livelihoods'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم', 'سبل العيش'],
    impact: '35,000+ families supported',
    impactAr: '35,000+ أسرة مدعومة',
    description: 'Major operations center with comprehensive humanitarian programs addressing refugee needs, healthcare, education, and economic empowerment.',
    descriptionAr: 'مركز عمليات رئيسي ببرامج إنسانية شاملة تعالج احتياجات اللاجئين والرعاية الصحية والتعليم والتمكين الاقتصادي.',
    office: 'Beirut Regional Headquarters',
    officeAr: 'مقر بيروت الإقليمي',
  },
  {
    id: 10,
    slug: 'palestine',
    name: 'Palestine',
    nameAr: 'فلسطين',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇵🇸',
    programs: ['Crisis Response', 'Healthcare', 'Education', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'التعليم', 'الأمن الغذائي'],
    impact: '32,000+ people supported',
    impactAr: '32,000+ شخص مدعوم',
    description: 'Emergency humanitarian assistance, medical services, educational support, and food distribution to vulnerable populations.',
    descriptionAr: 'مساعدة إنسانية طارئة وخدمات طبية ودعم تعليمي وتوزيع غذاء للفئات الضعيفة.',
    office: 'Gaza & West Bank Operations',
    officeAr: 'عمليات غزة والضفة الغربية',
  },
  {
    id: 11,
    slug: 'pakistan',
    name: 'Pakistan',
    nameAr: 'باكستان',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇵🇰',
    programs: ['Disaster Relief', 'Healthcare', 'Education', 'Livelihoods'],
    programsAr: ['إغاثة الكوارث', 'الرعاية الصحية', 'التعليم', 'سبل العيش'],
    impact: '22,000+ beneficiaries',
    impactAr: '22,000+ مستفيد',
    description: 'Flood and disaster relief operations, healthcare clinics, education programs, and vocational training initiatives.',
    descriptionAr: 'عمليات إغاثة الفيضانات والكوارث، عيادات الرعاية الصحية، برامج التعليم، ومبادرات التدريب المهني.',
    office: 'Islamabad Humanitarian Center',
    officeAr: 'مركز إسلام أباد الإنساني',
  },
  {
    id: 12,
    slug: 'philippines',
    name: 'Philippines',
    nameAr: 'الفلبين',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇵🇭',
    programs: ['Disaster Relief', 'Healthcare', 'Livelihood Training'],
    programsAr: ['إغاثة الكوارث', 'الرعاية الصحية', 'تدريب سبل العيش'],
    impact: '18,000+ typhoon survivors assisted',
    impactAr: '18,000+ ناجي من الأعاصير مساعدة',
    description: 'Typhoon disaster response, medical services, and economic empowerment programs for affected communities.',
    descriptionAr: 'استجابة لكوارث الأعاصير، خدمات طبية، وبرامج التمكين الاقتصادي للمجتمعات المتأثرة.',
    office: 'Manila Operations Center',
    officeAr: 'مركز مانيلا التشغيلي',
  },
  {
    id: 13,
    slug: 'sri-lanka',
    name: 'Sri Lanka',
    nameAr: 'سري لانكا',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇱🇰',
    programs: ['Healthcare', 'Education', 'Livelihood Support'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'دعم سبل العيش'],
    impact: '7,500+ beneficiaries',
    impactAr: '7,500+ مستفيد',
    description: 'Healthcare delivery, educational scholarships, and income-generating activity support.',
    descriptionAr: 'توصيل الرعاية الصحية والمنح الدراسية ودعم الأنشطة المدرة للدخل.',
    office: 'Colombo Regional Office',
    officeAr: 'مكتب كولومبو الإقليمي',
  },
  {
    id: 14,
    slug: 'syria',
    name: 'Syria',
    nameAr: 'سوريا',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇸🇾',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم'],
    impact: '55,000+ crisis-affected supported',
    impactAr: '55,000+ متضرر من الأزمات مدعوم',
    description: 'Large-scale humanitarian response including emergency relief, healthcare, food assistance, and educational support.',
    descriptionAr: 'استجابة إنسانية واسعة النطاق تشمل الإغاثة الطارئة والرعاية الصحية والمساعدة الغذائية والدعم التعليمي.',
    office: 'Damascus Crisis Response Hub',
    officeAr: 'مركز دمشق للاستجابة للأزمات',
  },
  {
    id: 15,
    slug: 'taiwan',
    name: 'Taiwan',
    nameAr: 'تايوان',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇹🇼',
    programs: ['Education', 'Community Development'],
    programsAr: ['التعليم', 'تنمية المجتمع'],
    impact: '3,000+ students supported',
    impactAr: '3,000+ طالب مدعوم',
    description: 'Educational programs and community development initiatives supporting vulnerable populations.',
    descriptionAr: 'برامج تعليمية ومبادرات تنمية المجتمع تدعم الفئات الضعيفة.',
    office: 'Taipei Coordination Office',
    officeAr: 'مكتب تايبيه التنسيقي',
  },
  {
    id: 16,
    slug: 'thailand',
    name: 'Thailand',
    nameAr: 'تايلاند',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇹🇭',
    programs: ['Healthcare', 'Education', 'Livelihood Training'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش'],
    impact: '9,000+ individuals served',
    impactAr: '9,000+ فرد مخدوم',
    description: 'Medical clinics, educational scholarships, and vocational training supporting vulnerable communities.',
    descriptionAr: 'عيادات طبية ومنح دراسية وتدريب مهني يدعم المجتمعات الضعيفة.',
    office: 'Bangkok Operations Office',
    officeAr: 'مكتب بانكوك التشغيلي',
  },
  {
    id: 17,
    slug: 'turkey',
    name: 'Turkey',
    nameAr: 'تركيا',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇹🇷',
    programs: ['Refugee Support', 'Healthcare', 'Education', 'Food Security'],
    programsAr: ['دعم اللاجئين', 'الرعاية الصحية', 'التعليم', 'الأمن الغذائي'],
    impact: '38,000+ Syrian refugees supported',
    impactAr: '38,000+ لاجئ سوري مدعوم',
    description: 'Comprehensive refugee support programs including shelter, healthcare, education, and livelihood assistance.',
    descriptionAr: 'برامج دعم اللاجئين الشاملة تشمل المأوى والرعاية الصحية والتعليم ودعم سبل العيش.',
    office: 'Istanbul Regional Hub',
    officeAr: 'مركز اسطنبول الإقليمي',
  },

  // AFRICA
  {
    id: 18,
    slug: 'algeria',
    name: 'Algeria',
    nameAr: 'الجزائر',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇩🇿',
    programs: ['Healthcare', 'Education', 'Food Security'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'الأمن الغذائي'],
    impact: '8,500+ families supported',
    impactAr: '8,500+ أسرة مدعومة',
    description: 'Healthcare clinics, educational programs, and food assistance for vulnerable populations.',
    descriptionAr: 'عيادات الرعاية الصحية والبرامج التعليمية والمساعدة الغذائية للفئات الضعيفة.',
    office: 'Algiers Regional Office',
    officeAr: 'مكتب الجزائر الإقليمي',
  },
  {
    id: 19,
    slug: 'comoros',
    name: 'Comoros Islands',
    nameAr: 'جزر القمر',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇰🇲',
    programs: ['Healthcare', 'Education', 'Disaster Relief'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'إغاثة الكوارث'],
    impact: '3,200+ beneficiaries',
    impactAr: '3,200+ مستفيد',
    description: 'Island-based medical and educational programs supporting isolated communities.',
    descriptionAr: 'برامج طبية وتعليمية قائمة على الجزر تدعم المجتمعات المعزولة.',
    office: 'Moroni Operations Center',
    officeAr: 'مركز موروني التشغيلي',
  },
  {
    id: 20,
    slug: 'congo',
    name: 'Congo',
    nameAr: 'الكونغو',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇨🇬',
    programs: ['Crisis Response', 'Healthcare', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'التعليم'],
    impact: '12,000+ crisis-affected supported',
    impactAr: '12,000+ متضرر من الأزمات مدعوم',
    description: 'Emergency humanitarian assistance and ongoing healthcare and education programs.',
    descriptionAr: 'مساعدة إنسانية طارئة وبرامج الرعاية الصحية والتعليم المستمرة.',
    office: 'Brazzaville Humanitarian Hub',
    officeAr: 'مركز برازافيل الإنساني',
  },
  {
    id: 21,
    slug: 'egypt',
    name: 'Egypt',
    nameAr: 'مصر',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇪🇬',
    programs: ['Healthcare', 'Education', 'Livelihood Training', 'Food Security'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش', 'الأمن الغذائي'],
    impact: '18,500+ beneficiaries',
    impactAr: '18,500+ مستفيد',
    description: 'Comprehensive medical clinics, educational scholarships, vocational training, and food assistance programs.',
    descriptionAr: 'عيادات طبية شاملة، منح دراسية، تدريب مهني، وبرامج المساعدة الغذائية.',
    office: 'Cairo Central Headquarters',
    officeAr: 'مقر القاهرة المركزي',
  },
  {
    id: 22,
    slug: 'ivory-coast',
    name: 'Ivory Coast',
    nameAr: 'ساحل العاج',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇨🇮',
    programs: ['Education', 'Healthcare', 'Livelihood Support'],
    programsAr: ['التعليم', 'الرعاية الصحية', 'دعم سبل العيش'],
    impact: '6,200+ students & workers trained',
    impactAr: '6,200+ طالب وعامل مُدرّب',
    description: 'Educational programs, medical clinics, and livelihood training for vulnerable populations.',
    descriptionAr: 'برامج تعليمية وعيادات طبية وتدريب سبل العيش للفئات الضعيفة.',
    office: 'Abidjan Regional Office',
    officeAr: 'مكتب أبيدجان الإقليمي',
  },
  {
    id: 23,
    slug: 'liberia',
    name: 'Liberia',
    nameAr: 'ليبيريا',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇱🇷',
    programs: ['Healthcare', 'Education', 'Livelihood Training'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش'],
    impact: '7,800+ beneficiaries',
    impactAr: '7,800+ مستفيد',
    description: 'Medical clinics, educational support, and vocational training programs.',
    descriptionAr: 'عيادات طبية ودعم تعليمي وبرامج تدريب مهني.',
    office: 'Monrovia Operations Center',
    officeAr: 'مركز مونروفيا التشغيلي',
  },
  {
    id: 24,
    slug: 'libya',
    name: 'Libya',
    nameAr: 'ليبيا',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇱🇾',
    programs: ['Crisis Response', 'Healthcare', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي'],
    impact: '16,500+ crisis-affected supported',
    impactAr: '16,500+ متضرر من الأزمات مدعوم',
    description: 'Emergency humanitarian assistance, medical support, and food distribution.',
    descriptionAr: 'مساعدة إنسانية طارئة ودعم طبي وتوزيع غذاء.',
    office: 'Tripoli Crisis Response Center',
    officeAr: 'مركز طرابلس للاستجابة للأزمات',
  },
  {
    id: 25,
    slug: 'morocco',
    name: 'Morocco',
    nameAr: 'المغرب',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇲🇦',
    programs: ['Healthcare', 'Education', 'Livelihood Training'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش'],
    impact: '9,100+ beneficiaries',
    impactAr: '9,100+ مستفيد',
    description: 'Healthcare clinics, educational scholarships, and vocational training initiatives.',
    descriptionAr: 'عيادات الرعاية الصحية والمنح الدراسية ومبادرات التدريب المهني.',
    office: 'Casablanca Regional Hub',
    officeAr: 'مركز الدار البيضاء الإقليمي',
  },
  {
    id: 26,
    slug: 'somalia',
    name: 'Somalia',
    nameAr: 'الصومال',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇸🇴',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم'],
    impact: '24,000+ crisis-affected supported',
    impactAr: '24,000+ متضرر من الأزمات مدعوم',
    description: 'Large-scale humanitarian programs addressing food insecurity, healthcare needs, and educational support.',
    descriptionAr: 'برامج إنسانية واسعة النطاق تعالج انعدام الأمن الغذائي واحتياجات الرعاية الصحية والدعم التعليمي.',
    office: 'Mogadishu Humanitarian Hub',
    officeAr: 'مركز مقديشو الإنساني',
  },
  {
    id: 27,
    slug: 'sudan',
    name: 'Sudan',
    nameAr: 'السودان',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇸🇩',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم'],
    impact: '42,000+ crisis-affected supported',
    impactAr: '42,000+ متضرر من الأزمات مدعوم',
    description: 'Major humanitarian operations including emergency relief, medical services, food assistance, and educational support.',
    descriptionAr: 'عمليات إنسانية كبرى تشمل الإغاثة الطارئة والخدمات الطبية والمساعدة الغذائية والدعم التعليمي.',
    office: 'Khartoum Emergency Operations',
    officeAr: 'عمليات الخرطوم الطارئة',
  },

  // EUROPE
  {
    id: 28,
    slug: 'abkhazia',
    name: 'Abkhazia',
    nameAr: 'أبخازيا',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇬🇪',
    programs: ['Crisis Response', 'Healthcare', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي'],
    impact: '5,500+ conflict-affected supported',
    impactAr: '5,500+ متضرر من الصراع مدعوم',
    description: 'Emergency humanitarian assistance to conflict-affected population.',
    descriptionAr: 'مساعدة إنسانية طارئة للسكان المتأثرين بالصراع.',
    office: 'Sukhumi Operations Center',
    officeAr: 'مركز سوخومي التشغيلي',
  },
  {
    id: 29,
    slug: 'bosnia',
    name: 'Bosnia',
    nameAr: 'البوسنة',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇧🇦',
    programs: ['Healthcare', 'Education', 'Livelihood Support'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'دعم سبل العيش'],
    impact: '6,800+ beneficiaries',
    impactAr: '6,800+ مستفيد',
    description: 'Post-conflict recovery programs including healthcare, education, and economic support.',
    descriptionAr: 'برامج التعافي بعد الصراع تشمل الرعاية الصحية والتعليم والدعم الاقتصادي.',
    office: 'Sarajevo Regional Office',
    officeAr: 'مكتب سراييفو الإقليمي',
  },
  {
    id: 30,
    slug: 'bulgaria',
    name: 'Bulgaria',
    nameAr: 'بلغاريا',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇧🇬',
    programs: ['Healthcare', 'Education'],
    programsAr: ['الرعاية الصحية', 'التعليم'],
    impact: '4,200+ beneficiaries',
    impactAr: '4,200+ مستفيد',
    description: 'Medical clinics and educational programs for vulnerable communities.',
    descriptionAr: 'عيادات طبية وبرامج تعليمية للمجتمعات الضعيفة.',
    office: 'Sofia Operations Office',
    officeAr: 'مكتب صوفيا التشغيلي',
  },
  {
    id: 31,
    slug: 'chechnya',
    name: 'Chechnya',
    nameAr: 'الشيشان',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇷🇺',
    programs: ['Crisis Response', 'Healthcare', 'Livelihood Support'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'دعم سبل العيش'],
    impact: '7,600+ conflict-affected supported',
    impactAr: '7,600+ متضرر من الصراع مدعوم',
    description: 'Humanitarian assistance for conflict-affected population including medical and economic support.',
    descriptionAr: 'المساعدة الإنسانية للسكان المتأثرين بالصراع تشمل الدعم الطبي والاقتصادي.',
    office: 'Grozny Emergency Hub',
    officeAr: 'مركز غروزني الطارئ',
  },
  {
    id: 32,
    slug: 'macedonia',
    name: 'Macedonia',
    nameAr: 'مقدونيا',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇲🇰',
    programs: ['Healthcare', 'Education', 'Livelihood Support'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'دعم سبل العيش'],
    impact: '5,300+ beneficiaries',
    impactAr: '5,300+ مستفيد',
    description: 'Healthcare delivery, educational scholarships, and livelihood programs.',
    descriptionAr: 'توصيل الرعاية الصحية والمنح الدراسية وبرامج سبل العيش.',
    office: 'Skopje Regional Center',
    officeAr: 'مركز سكوبيا الإقليمي',
  },
  {
    id: 33,
    slug: 'romania',
    name: 'Romania',
    nameAr: 'رومانيا',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇷🇴',
    programs: ['Healthcare', 'Education'],
    programsAr: ['الرعاية الصحية', 'التعليم'],
    impact: '4,900+ beneficiaries',
    impactAr: '4,900+ مستفيد',
    description: 'Medical clinics and educational support for vulnerable populations.',
    descriptionAr: 'عيادات طبية ودعم تعليمي للفئات الضعيفة.',
    office: 'Bucharest Operations Office',
    officeAr: 'مكتب بوخارست التشغيلي',
  },
  {
    id: 34,
    slug: 'south-ossetia',
    name: 'South Ossetia',
    nameAr: 'أوسيتيا الجنوبية',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇬🇪',
    programs: ['Crisis Response', 'Healthcare', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي'],
    impact: '4,800+ conflict-affected supported',
    impactAr: '4,800+ متضرر من الصراع مدعوم',
    description: 'Emergency humanitarian assistance to conflict-affected communities.',
    descriptionAr: 'مساعدة إنسانية طارئة للمجتمعات المتأثرة بالصراع.',
    office: 'Tskhinvali Operations',
    officeAr: 'عمليات تسخينفالي',
  },

  // AMERICAS
  {
    id: 35,
    slug: 'haiti',
    name: 'Haiti',
    nameAr: 'هايتي',
    region: 'americas',
    regionAr: 'الأمريكتان',
    flag: '🇭🇹',
    programs: ['Disaster Relief', 'Healthcare', 'Education', 'Livelihood Training'],
    programsAr: ['إغاثة الكوارث', 'الرعاية الصحية', 'التعليم', 'تدريب سبل العيش'],
    impact: '28,000+ hurricane survivors supported',
    impactAr: '28,000+ ناجي من الأعاصير مدعوم',
    description: 'Comprehensive disaster relief operations, healthcare clinics, educational scholarships, and vocational training programs.',
    descriptionAr: 'عمليات إغاثة كوارث شاملة وعيادات طبية ومنح دراسية وبرامج تدريب مهني.',
    office: 'Port-au-Prince Coordination Hub',
    officeAr: 'مركز بورت أو برنس التنسيقي',
  },
];

export const mobileApps = [
  {
    id: 1,
    slug: 'jhco-connect',
    name: 'JHCO Connect',
    nameAr: 'الهيئة تتصل',
    description: 'Donate, volunteer, and stay updated on JHCO initiatives with our main mobile app',
    descriptionAr: 'تبرع وتطوع وابق محدثاً بشأن مبادرات الهيئة من خلال تطبيق الهاتف المحمول الخاص بنا',
    longDescription: 'The official JHCO Connect app provides seamless access to donation features, volunteer opportunities, real-time impact tracking, and exclusive updates from the field. Stay connected with our humanitarian mission wherever you are.',
    longDescriptionAr: 'يوفر تطبيق JHCO Connect الرسمي الوصول السلس إلى ميزات التبرع وفرص التطوع وتتبع التأثير في الوقت الفعلي والتحديثات الحصرية من الميدان. ابق متصلاً بمهمتنا الإنسانية أينما كنت.',
    features: ['Quick Donation', 'Volunteer Signup', 'Impact Tracking', 'Push Notifications', 'Offline Access', 'Multi-language Support'],
    featuresAr: ['التبرع السريع', 'التسجيل للتطوع', 'تتبع التأثير', 'إشعارات فورية', 'الوصول بدون اتصال', 'دعم اللغات المتعددة'],
    rating: 4.8,
    reviews: 2547,
    downloads: '100K+',
    category: 'Main App',
    categoryAr: 'التطبيق الرئيسي',
    icon: '📱',
  },
  {
    id: 2,
    slug: 'jhco-donor',
    name: 'JHCO Donor',
    nameAr: 'المتبرع الخيري',
    description: 'Advanced donor portal for tracking contributions and receiving detailed impact reports',
    descriptionAr: 'بوابة متقدمة للمانحين لتتبع المساهمات وتلقي تقارير تأثير مفصلة',
    longDescription: 'Exclusively designed for our valued donors, JHCO Donor provides comprehensive dashboards, tax documentation, impact reports, and direct communication channels with our programs. Watch your contribution make a difference.',
    longDescriptionAr: 'مصمم خصيصاً لمانحينا الموقرين، يوفر تطبيق المتبرع الخيري لوحات معلومات شاملة وتوثيق ضريبي وتقارير التأثير وقنوات اتصال مباشرة مع برامجنا. شاهد مساهمتك تحدث فرقاً.',
    features: ['Donation History', 'Tax Documents', 'Impact Reports', 'Program Updates', 'Direct Messaging', 'Receipt Management'],
    featuresAr: ['سجل التبرعات', 'المستندات الضريبية', 'تقارير التأثير', 'تحديثات البرنامج', 'الرسائل المباشرة', 'إدارة الإيصالات'],
    rating: 4.9,
    reviews: 1834,
    downloads: '50K+',
    category: 'Donor Tools',
    categoryAr: 'أدوات المانحين',
    icon: '💳',
  },
  {
    id: 3,
    slug: 'jhco-volunteer',
    name: 'JHCO Volunteer',
    nameAr: 'متطوع الهيئة',
    description: 'Comprehensive volunteer management app with scheduling, training, and coordination features',
    descriptionAr: 'تطبيق شامل لإدارة المتطوعين مع ميزات الجدولة والتدريب والتنسيق',
    longDescription: 'The ultimate companion for JHCO volunteers, featuring shift scheduling, task assignments, training materials, team communication, and real-time coordination of humanitarian efforts across the globe.',
    longDescriptionAr: 'الرفيق النهائي لمتطوعي الهيئة، يتضمن جدولة الفترات وتعيين المهام والمواد التدريبية واتصالات الفريق والتنسيق الفعلي للجهود الإنسانية حول العالم.',
    features: ['Shift Scheduling', 'Task Management', 'Training Portal', 'Team Chat', 'Impact Tracking', 'Certification'],
    featuresAr: ['جدولة الفترات', 'إدارة المهام', 'بوابة التدريب', 'دردشة الفريق', 'تتبع التأثير', 'الشهادات'],
    rating: 4.7,
    reviews: 3125,
    downloads: '75K+',
    category: 'Volunteer Tools',
    categoryAr: 'أدوات المتطوعين',
    icon: '🤝',
  },
  {
    id: 4,
    slug: 'jhco-beneficiary',
    name: 'JHCO Beneficiary',
    nameAr: 'المستفيد من الهيئة',
    description: 'Support app for program beneficiaries to access services and track assistance',
    descriptionAr: 'تطبيق الدعم للمستفيدين من البرامج للوصول إلى الخدمات وتتبع المساعدة',
    longDescription: 'Empowering beneficiaries of our programs with direct access to services, appointment scheduling, resource directory, education materials, and real-time support from JHCO staff.',
    longDescriptionAr: 'تمكين المستفيدين من برامجنا بالوصول المباشر إلى الخدمات وجدولة المواعيد ودليل الموارد والمواد التعليمية والدعم الفعلي من موظفي الهيئة.',
    features: ['Service Access', 'Appointment Booking', 'Resource Library', 'Educational Content', 'Support Chat', 'Progress Tracking'],
    featuresAr: ['الوصول إلى الخدمات', 'حجز المواعيد', 'مكتبة الموارد', 'المحتوى التعليمي', 'دردشة الدعم', 'تتبع التقدم'],
    rating: 4.6,
    reviews: 2156,
    downloads: '60K+',
    category: 'Beneficiary Portal',
    categoryAr: 'بوابة المستفيدين',
    icon: '🎯',
  },
  {
    id: 5,
    slug: 'jhco-field-ops',
    name: 'JHCO Field Ops',
    nameAr: 'عمليات الهيئة الميدانية',
    description: 'Real-time field operations management for coordinating humanitarian efforts',
    descriptionAr: 'إدارة العمليات الميدانية الفعلية لتنسيق الجهود الإنسانية',
    longDescription: 'Built for field coordinators and operational teams, JHCO Field Ops enables real-time GPS tracking, supply inventory management, incident reporting, and team coordination across multiple regions.',
    longDescriptionAr: 'مُنشأ لمنسقي الميدان والفرق التشغيلية، يوفر تطبيق العمليات الميدانية تتبعاً فعلياً بنظام GPS وإدارة مخزون الإمدادات والإبلاغ عن الحوادث والتنسيق بين الفرق عبر عدة مناطق.',
    features: ['GPS Tracking', 'Inventory Management', 'Incident Reporting', 'Team Coordination', 'Geofencing', 'Offline Maps'],
    featuresAr: ['تتبع GPS', 'إدارة المخزون', 'الإبلاغ عن الحوادث', 'تنسيق الفريق', 'الحدود الجغرافية', 'الخرائط بدون اتصال'],
    rating: 4.5,
    reviews: 892,
    downloads: '25K+',
    category: 'Operations',
    categoryAr: 'العمليات',
    icon: '🗺️',
  },
  {
    id: 6,
    slug: 'jhco-education',
    name: 'JHCO Education Hub',
    nameAr: 'مركز التعليم الخيري',
    description: 'Learning platform for educational programs and scholarship management',
    descriptionAr: 'منصة التعلم لبرامج التعليم وإدارة المنح الدراسية',
    longDescription: 'Comprehensive education platform featuring online courses, scholarship applications, progress tracking, mentorship connections, and career development resources for students enrolled in JHCO programs.',
    longDescriptionAr: 'منصة تعليمية شاملة تتضمن دورات عبر الإنترنت وطلبات المنح الدراسية وتتبع التقدم وتوصيلات الإرشاد وموارد التطوير الوظيفي للطلاب المسجلين في برامج الهيئة.',
    features: ['Online Courses', 'Scholarship Portal', 'Progress Tracking', 'Mentorship', 'Career Resources', 'Peer Community'],
    featuresAr: ['الدورات عبر الإنترنت', 'بوابة المنح', 'تتبع التقدم', 'الإرشاد', 'موارد الوظائف', 'مجتمع الأقران'],
    rating: 4.7,
    reviews: 1432,
    downloads: '40K+',
    category: 'Education',
    categoryAr: 'التعليم',
    icon: '📚',
  },
];

export const volunteerOpportunities = [
  {
    id: 1,
    slug: 'field-coordinator-gaza',
    title: 'Field Coordinator - Gaza',
    titleAr: 'منسق ميداني - غزة',
    category: 'Field',
    categoryAr: 'ميداني',
    type: 'On-Site',
    typeAr: 'في الموقع',
    location: 'Gaza Strip',
    locationAr: 'قطاع غزة',
    commitment: '3-6 months',
    commitmentAr: '3-6 أشهر',
    description: 'Coordinate humanitarian relief operations in Gaza, managing logistics, distribution, and community engagement.',
    descriptionAr: 'تنسيق عمليات الإغاثة الإنسانية في غزة، إدارة الخدمات اللوجستية والتوزيع والتفاعل المجتمعي.',
    requirements: ['2+ years project management experience', 'Arabic language skills', 'Crisis management experience', 'Flexibility and adaptability'],
    requirementsAr: ['خبرة 2+ سنة في إدارة المشاريع', 'مهارات اللغة العربية', 'خبرة في إدارة الأزمات', 'المرونة والقدرة على التكيف'],
    skills: ['Project Management', 'Leadership', 'Communication', 'Crisis Management'],
    skillsAr: ['إدارة المشاريع', 'القيادة', 'التواصل', 'إدارة الأزمات'],
    impact: 'Direct impact on 5,000+ families',
    impactAr: 'تأثير مباشر على 5,000+ أسرة',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🌍',
  },
  {
    id: 2,
    slug: 'healthcare-volunteer',
    title: 'Healthcare Volunteer - Medical Clinics',
    titleAr: 'متطوع الرعاية الصحية - العيادات الطبية',
    category: 'Field',
    categoryAr: 'ميداني',
    type: 'On-Site',
    typeAr: 'في الموقع',
    location: 'Multiple Regions',
    locationAr: 'مناطق متعددة',
    commitment: '2-4 months',
    commitmentAr: '2-4 أشهر',
    description: 'Support healthcare delivery in our medical clinics across regions. Assist doctors and nurses in patient care.',
    descriptionAr: 'دعم تقديم الرعاية الصحية في عياداتنا الطبية عبر المناطق. مساعدة الأطباء والممرضات في رعاية المرضى.',
    requirements: ['Medical background preferred', 'Basic healthcare knowledge', 'Compassion for vulnerable populations', 'Physical stamina'],
    requirementsAr: ['خلفية طبية مفضلة', 'معرفة أساسية بالرعاية الصحية', 'التعاطف مع الفئات الضعيفة', 'القدرة على البقاء واقفاً'],
    skills: ['Healthcare', 'Patient Care', 'Empathy', 'Physical Health'],
    skillsAr: ['الرعاية الصحية', 'رعاية المرضى', 'التعاطف', 'الصحة البدنية'],
    impact: 'Support 3,000+ patient visits',
    impactAr: 'دعم 3,000+ زيارة مريض',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🏥',
  },
  {
    id: 3,
    slug: 'education-tutor-remote',
    title: 'Education Tutor - Remote',
    titleAr: 'معلم دروس خصوصية - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '10-15 hours/week',
    commitmentAr: '10-15 ساعة/أسبوع',
    description: 'Provide online tutoring to students in underserved communities. Help them excel in core subjects.',
    descriptionAr: 'تقديم دروس خصوصية عبر الإنترنت للطلاب في المجتمعات الفقيرة. ساعدهم في التفوق في المواد الأساسية.',
    requirements: ['Teaching experience', 'Subject matter expertise', 'Online communication skills', 'Patience and dedication'],
    requirementsAr: ['خبرة تعليمية', 'خبرة متخصصة', 'مهارات التواصل عبر الإنترنت', 'الصبر والتفاني'],
    skills: ['Teaching', 'Communication', 'Patience', 'Subject Knowledge'],
    skillsAr: ['التدريس', 'التواصل', 'الصبر', 'المعرفة المتخصصة'],
    impact: 'Help 200+ students improve grades',
    impactAr: 'ساعد 200+ طالب على تحسين الدرجات',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🎓',
  },
  {
    id: 4,
    slug: 'data-analyst-remote',
    title: 'Data Analyst - Remote',
    titleAr: 'محلل بيانات - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '15-20 hours/week',
    commitmentAr: '15-20 ساعة/أسبوع',
    description: 'Analyze program impact data and create insights to improve humanitarian initiatives effectiveness.',
    descriptionAr: 'تحليل بيانات تأثير البرنامج وإنشاء رؤى لتحسين فعالية المبادرات الإنسانية.',
    requirements: ['Data analysis expertise', 'Excel/SQL proficiency', 'Attention to detail', 'Reporting skills'],
    requirementsAr: ['خبرة تحليل البيانات', 'إتقان Excel/SQL', 'الاهتمام بالتفاصيل', 'مهارات الإبلاغ'],
    skills: ['Data Analysis', 'Excel', 'SQL', 'Communication'],
    skillsAr: ['تحليل البيانات', 'Excel', 'SQL', 'التواصل'],
    impact: 'Improve program efficiency for 15+ initiatives',
    impactAr: 'تحسين كفاءة البرنامج لـ 15+ مبادرة',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '📊',
  },
  {
    id: 5,
    slug: 'content-writer-remote',
    title: 'Content Writer - Remote',
    titleAr: 'كاتب محتوى - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '8-12 hours/week',
    commitmentAr: '8-12 ساعة/أسبوع',
    description: 'Create compelling stories about our humanitarian work and volunteer experiences. Help amplify our impact.',
    descriptionAr: 'إنشاء قصص جذابة عن عملنا الإنساني وتجارب المتطوعين. ساعد في تضخيم تأثيرنا.',
    requirements: ['Excellent writing skills', 'Storytelling ability', 'Bilingual (English/Arabic) preferred', 'Social media knowledge'],
    requirementsAr: ['مهارات الكتابة الممتازة', 'القدرة على سرد القصص', 'ثنائي اللغة (إنجليزي/عربي) مفضل', 'معرفة وسائل التواصل الاجتماعي'],
    skills: ['Writing', 'Storytelling', 'Communication', 'Social Media'],
    skillsAr: ['الكتابة', 'سرد القصص', 'التواصل', 'وسائل التواصل الاجتماعي'],
    impact: 'Reach 50,000+ people monthly with stories',
    impactAr: 'الوصول إلى 50,000+ شخص شهرياً بالقصص',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '✍️',
  },
  {
    id: 6,
    slug: 'graphic-designer-remote',
    title: 'Graphic Designer - Remote',
    titleAr: 'مصمم جرافيك - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '12-16 hours/week',
    commitmentAr: '12-16 ساعة/أسبوع',
    description: 'Design visual materials for campaigns and communications. Create engaging graphics for social media and reports.',
    descriptionAr: 'تصميم المواد البصرية للحملات والاتصالات. إنشاء رسومات جذابة لوسائل التواصل الاجتماعي والتقارير.',
    requirements: ['Graphic design expertise', 'Proficiency in design software', 'Creative thinking', 'Brand understanding'],
    requirementsAr: ['خبرة تصميم جرافيك', 'إتقان برامج التصميم', 'التفكير الإبداعي', 'فهم العلامة التجارية'],
    skills: ['Graphic Design', 'Adobe Suite', 'Creativity', 'Brand Design'],
    skillsAr: ['تصميم جرافيك', 'Adobe Suite', 'الإبداع', 'تصميم العلامة التجارية'],
    impact: 'Create 50+ design assets monthly',
    impactAr: 'إنشاء 50+ أصل تصميمي شهرياً',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🎨',
  },
  {
    id: 7,
    slug: 'translator-remote',
    title: 'Translator - Remote (Arabic/English)',
    titleAr: 'مترجم - عن بُعد (عربي/إنجليزي)',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '10-20 hours/week',
    commitmentAr: '10-20 ساعة/أسبوع',
    description: 'Translate documents, reports, and communications between Arabic and English. Bridge language barriers in our work.',
    descriptionAr: 'ترجمة المستندات والتقارير والاتصالات بين العربية والإنجليزية. تجسير الفجوات اللغوية في عملنا.',
    requirements: ['Native/fluent in Arabic and English', 'Translation experience', 'Cultural sensitivity', 'Attention to detail'],
    requirementsAr: ['أصلي/بطلاقة في العربية والإنجليزية', 'خبرة الترجمة', 'الحساسية الثقافية', 'الاهتمام بالتفاصيل'],
    skills: ['Translation', 'Arabic', 'English', 'Communication'],
    skillsAr: ['الترجمة', 'العربية', 'الإنجليزية', 'التواصل'],
    impact: 'Translate 100+ documents monthly',
    impactAr: 'ترجمة 100+ مستند شهرياً',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🌐',
  },
  {
    id: 8,
    slug: 'administrative-support',
    title: 'Administrative Support - Remote',
    titleAr: 'الدعم الإداري - عن بُعد',
    category: 'Administrative',
    categoryAr: 'إداري',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '12-15 hours/week',
    commitmentAr: '12-15 ساعة/أسبوع',
    description: 'Provide administrative support including scheduling, email management, and document organization.',
    descriptionAr: 'تقديم الدعم الإداري بما فيه جدولة المواعيد وإدارة البريد الإلكتروني وتنظيم المستندات.',
    requirements: ['Organizational skills', 'Office software proficiency', 'Attention to detail', 'Communication skills'],
    requirementsAr: ['مهارات تنظيمية', 'إتقان برامج المكتب', 'الاهتمام بالتفاصيل', 'مهارات التواصل'],
    skills: ['Organization', 'Office Management', 'Communication', 'Problem Solving'],
    skillsAr: ['التنظيم', 'إدارة المكتب', 'التواصل', 'حل المشاكل'],
    impact: 'Support 5+ teams efficiently',
    impactAr: 'دعم 5+ فرق بكفاءة',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '📋',
  },
  {
    id: 9,
    slug: 'social-media-manager',
    title: 'Social Media Manager - Remote',
    titleAr: 'مدير وسائل التواصل - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '15-20 hours/week',
    commitmentAr: '15-20 ساعة/أسبوع',
    description: 'Manage our social media accounts, create engaging content, and grow our online community.',
    descriptionAr: 'إدارة حساباتنا على وسائل التواصل والمحتوى الجذاب وتنمية مجتمعنا عبر الإنترنت.',
    requirements: ['Social media expertise', 'Content creation skills', 'Analytics knowledge', 'Community management experience'],
    requirementsAr: ['خبرة وسائل التواصل', 'مهارات إنشاء المحتوى', 'معرفة التحليلات', 'خبرة إدارة المجتمع'],
    skills: ['Social Media', 'Content Creation', 'Analytics', 'Community Management'],
    skillsAr: ['وسائل التواصل', 'إنشاء المحتوى', 'التحليلات', 'إدارة المجتمع'],
    impact: 'Reach 100,000+ followers',
    impactAr: 'الوصول إلى 100,000+ متابع',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '📱',
  },
  {
    id: 10,
    slug: 'youth-mentor-field',
    title: 'Youth Mentor - Field Program',
    titleAr: 'مرشد شباب - برنامج ميداني',
    category: 'Field',
    categoryAr: 'ميداني',
    type: 'On-Site',
    typeAr: 'في الموقع',
    location: 'Multiple Regions',
    locationAr: 'مناطق متعددة',
    commitment: '3-4 months',
    commitmentAr: '3-4 أشهر',
    description: 'Mentor young people in skill development and career guidance. Help them achieve their potential.',
    descriptionAr: 'إرشاد الشباب في تطوير المهارات والتوجيه المهني. ساعدهم على تحقيق إمكاناتهم.',
    requirements: ['Mentoring experience', 'Leadership skills', 'Passion for youth development', 'Patience and empathy'],
    requirementsAr: ['خبرة الإرشاد', 'مهارات القيادة', 'الشغف بتطوير الشباب', 'الصبر والتعاطف'],
    skills: ['Mentoring', 'Leadership', 'Communication', 'Youth Development'],
    skillsAr: ['الإرشاد', 'القيادة', 'التواصل', 'تطوير الشباب'],
    impact: 'Guide 150+ young people',
    impactAr: 'إرشاد 150+ شاب',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '👥',
  },
  {
    id: 11,
    slug: 'logistics-coordinator',
    title: 'Logistics Coordinator - Field',
    titleAr: 'منسق الخدمات اللوجستية - ميداني',
    category: 'Field',
    categoryAr: 'ميداني',
    type: 'On-Site',
    typeAr: 'في الموقع',
    location: 'Multiple Regions',
    locationAr: 'مناطق متعددة',
    commitment: '4-6 months',
    commitmentAr: '4-6 أشهر',
    description: 'Coordinate supplies, equipment, and distribution logistics for humanitarian operations.',
    descriptionAr: 'تنسيق المستلزمات والمعدات والخدمات اللوجستية للتوزيع للعمليات الإنسانية.',
    requirements: ['Logistics experience', 'Problem-solving skills', 'Attention to detail', 'Physical capability'],
    requirementsAr: ['خبرة لوجستية', 'مهارات حل المشاكل', 'الاهتمام بالتفاصيل', 'القدرة البدنية'],
    skills: ['Logistics', 'Organization', 'Problem Solving', 'Leadership'],
    skillsAr: ['الخدمات اللوجستية', 'التنظيم', 'حل المشاكل', 'القيادة'],
    impact: 'Deliver 10,000+ aid packages',
    impactAr: 'توصيل 10,000+ حزمة إغاثة',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '📦',
  },
  {
    id: 12,
    slug: 'web-developer-remote',
    title: 'Web Developer - Remote',
    titleAr: 'مطور ويب - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '15-20 hours/week',
    commitmentAr: '15-20 ساعة/أسبوع',
    description: 'Develop and maintain web applications that help manage our programs and reach beneficiaries.',
    descriptionAr: 'تطوير والحفاظ على تطبيقات ويب تساعد في إدارة برامجنا والوصول إلى المستفيدين.',
    requirements: ['Web development experience', 'JavaScript proficiency', 'Problem-solving skills', 'Git knowledge'],
    requirementsAr: ['خبرة تطوير الويب', 'إتقان JavaScript', 'مهارات حل المشاكل', 'معرفة Git'],
    skills: ['Web Development', 'JavaScript', 'React/Vue', 'Database Design'],
    skillsAr: ['تطوير الويب', 'JavaScript', 'React/Vue', 'تصميم قواعد البيانات'],
    impact: 'Improve digital reach for 100,000+ users',
    impactAr: 'تحسين الوصول الرقمي لـ 100,000+ مستخدم',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '💻',
  },
];
