export const impactStats = [
  { value: '75,000+', label: 'Families Supported', labelAr: 'الأسر المدعومة' },
  { value: '30+', label: 'Countries Reached', labelAr: 'الدول المخدومة' },
  { value: '2,500+', label: 'Volunteers Active', labelAr: 'المتطوعون النشطون' },
  { value: '50+', label: 'Programs Running', labelAr: 'البرامج الفعّالة' },
];

export const royalInitiatives = [
  {
    id: 1,
    slug: 'bahrain-gaza-partnership',
    name: 'Bahrain Royal Charity Organisation Partnership - Gaza',
    nameAr: 'شراكة مؤسسة البحرين الملكية للأعمال الخيرية - غزة',
    description: 'Joint humanitarian initiative with Bahrain Royal Charity Organisation providing emergency relief to Gaza',
    descriptionAr: 'مبادرة إنسانية مشتركة مع مؤسسة البحرين الملكية للأعمال الخيرية توفر الإغاثة الطارئة إلى غزة',
    longDescription: 'A landmark cooperation agreement signed between JHCO and the Bahrain Royal Charity Organisation to provide comprehensive humanitarian assistance to families affected by the crisis in Gaza, including emergency relief, medical aid, food security, and shelter support.',
    longDescriptionAr: 'اتفاقية تعاون تاريخية وقعتها الهيئة ومؤسسة البحرين الملكية للأعمال الخيرية لتقديم مساعدة إنسانية شاملة للأسر المتضررة من الأزمة في غزة، تشمل الإغاثة الطارئة والمساعدة الطبية والأمن الغذائي ودعم المأوى.',
    category: 'Royal Partnerships',
    categoryAr: 'الشراكات الملكية',
    impact: '20,000+ families supported',
    impactAr: '20,000+ أسرة مدعومة',
    status: 'Active',
    partner: 'Bahrain Royal Charity Organisation',
    partnerAr: 'مؤسسة البحرين الملكية للأعمال الخيرية',
    objectives: ['Emergency relief provision', 'Medical assistance', 'Food security', 'Shelter support', 'Rehabilitation services'],
    objectivesAr: ['توفير الإغاثة الطارئة', 'المساعدة الطبية', 'الأمن الغذائي', 'دعم المأوى', 'خدمات إعادة التأهيل'],
  },
  {
    id: 2,
    slug: 'royal-education-initiative',
    name: 'Royal Education Enhancement Program',
    nameAr: 'برنامج تعزيز التعليم الملكي',
    description: 'Premium educational scholarship program funded by royal patronage across multiple regions',
    descriptionAr: 'برنامج منح دراسية متميز ممول برعاية ملكية عبر عدة مناطق',
    longDescription: 'A prestigious educational initiative providing premium scholarships, advanced learning materials, and mentorship programs to exceptional students from underprivileged backgrounds, supported by royal patronage and institutional grants.',
    longDescriptionAr: 'مبادرة تعليمية مرموقة توفر منح دراسية متميزة ومواد تعليمية متقدمة وبرامج إرشادية للطلاب المتفوقين من خلفيات محرومة، مدعومة برعاية ملكية ومنح مؤسسية.',
    category: 'Royal Education',
    categoryAr: 'التعليم الملكي',
    impact: '5,200+ students empowered',
    impactAr: '5,200+ طالب مُمكّن',
    status: 'Active',
    partner: 'Royal Education Foundation',
    partnerAr: 'مؤسسة التعليم الملكية',
    objectives: ['Scholarship distribution', 'Mentorship programs', 'Advanced learning materials', 'Capacity building', 'International exchange'],
    objectivesAr: ['توزيع المنح', 'برامج الإرشاد', 'مواد التعليم المتقدمة', 'بناء القدرات', 'التبادل الدولي'],
  },
  {
    id: 3,
    slug: 'royal-healthcare-excellence',
    name: 'Royal Healthcare Excellence Initiative',
    nameAr: 'مبادرة التميز الصحي الملكي',
    description: 'State-of-the-art medical facilities and specialist services supported by royal patronage',
    descriptionAr: 'منشآت طبية متقدمة وخدمات متخصصة مدعومة برعاية ملكية',
    longDescription: 'A comprehensive healthcare initiative establishing specialized medical centers and clinics with advanced equipment, specialist doctors, and comprehensive treatment programs for underserved populations, backed by royal patronage and institutional support.',
    longDescriptionAr: 'مبادرة صحية شاملة تنشئ مراكز طبية متخصصة وعيادات بمعدات متقدمة وأطباء متخصصين وبرامج علاج شاملة للسكان غير المخدومين، مدعومة برعاية ملكية ودعم مؤسسي.',
    category: 'Royal Healthcare',
    categoryAr: 'الرعاية الصحية الملكية',
    impact: '18,000+ treated annually',
    impactAr: '18,000+ مريض سنوياً',
    status: 'Active',
    partner: 'Royal Medical Authority',
    partnerAr: 'الهيئة الطبية الملكية',
    objectives: ['Specialized medical centers', 'Advanced diagnostics', 'Surgical services', 'Specialist consultation', 'Medical research'],
    objectivesAr: ['مراكز طبية متخصصة', 'التشخيص المتقدم', 'الخدمات الجراحية', 'الاستشارة المتخصصة', 'البحث الطبي'],
  },
  {
    id: 4,
    slug: 'royal-women-empowerment',
    name: 'Royal Women Empowerment & Leadership Program',
    nameAr: 'برنامج تمكين النساء والقيادة الملكي',
    description: 'Empowerment and leadership development for women under royal patronage',
    descriptionAr: 'التمكين وتطوير القيادة للنساء تحت الرعاية الملكية',
    longDescription: 'A prestigious program providing comprehensive training, business development support, and leadership development to women from disadvantaged communities, enabling economic independence and social leadership under royal patronage.',
    longDescriptionAr: 'برنامج مرموق يوفر تدريباً شاملاً ودعماً لتطوير الأعمال وتطوير القيادة للنساء من المجتمعات المحرومة، يمكنهن من الاستقلال الاقتصادي والقيادة الاجتماعية تحت الرعاية الملكية.',
    category: 'Royal Empowerment',
    categoryAr: 'التمكين الملكي',
    impact: '3,500+ women empowered',
    impactAr: '3,500+ امرأة مُمكّنة',
    status: 'Active',
    partner: 'Royal Women Foundation',
    partnerAr: 'مؤسسة النساء الملكية',
    objectives: ['Business training', 'Microfinance access', 'Leadership development', 'Mentorship', 'Market access support'],
    objectivesAr: ['تدريب الأعمال', 'الوصول إلى التمويل الأصغر', 'تطوير القيادة', 'الإرشاد', 'دعم الوصول إلى السوق'],
  },
  {
    id: 5,
    slug: 'royal-youth-development',
    name: 'Royal Youth Development & Skills Initiative',
    nameAr: 'مبادرة تطوير الشباب والمهارات الملكية',
    description: 'Comprehensive youth development program combining skills training, mentorship, and career placement',
    descriptionAr: 'برنامج تطوير شباب شامل يجمع بين تدريب المهارات والإرشاد والتوظيف',
    longDescription: 'A premier youth development initiative providing comprehensive vocational training, internship opportunities, mentorship from industry leaders, and career placement assistance to young people, supported by royal patronage and institutional partnerships.',
    longDescriptionAr: 'مبادرة تطوير شباب برتبة عالية توفر تدريباً مهنياً شاملاً وفرص تدريب داخلي وإرشاداً من قادة الصناعة والمساعدة على التوظيف، مدعومة برعاية ملكية وشراكات مؤسسية.',
    category: 'Royal Youth Programs',
    categoryAr: 'برامج الشباب الملكية',
    impact: '7,800+ youth trained',
    impactAr: '7,800+ شاب مُدرّب',
    status: 'Active',
    partner: 'Royal Youth Foundation',
    partnerAr: 'مؤسسة الشباب الملكية',
    objectives: ['Vocational training', 'Internship placement', 'Mentorship programs', 'Career counseling', 'Job placement'],
    objectivesAr: ['التدريب المهني', 'توظيف التدريب الداخلي', 'برامج الإرشاد', 'الاستشارة الوظيفية', 'توظيف الوظائف'],
  },
];

export const programs = [
  {
    id: 1,
    slug: 'gaza-aid',
    name: 'For Our People in Gaza',
    nameAr: 'لأهلنا في غزة',
    description: 'Providing immediate humanitarian assistance to families affected by the crisis in Gaza',
    descriptionAr: 'توفير المساعدة الإنسانية الفورية للأسر المتضررة من الأزمة في غزة',
    longDescription: 'JHCO continues to provide humanitarian aid and support to families in Gaza affected by ongoing crisis. Our programs focus on emergency relief, medical assistance, and essential supplies to ensure human dignity.',
    longDescriptionAr: 'تواصل الهيئة تقديم المساعدات الإنسانية والدعم للأسر في غزة المتضررة من الأزمة المستمرة. تركز برامجنا على الإغاثة الطارئة والمساعدة الطبية والإمدادات الأساسية لضمان الكرامة الإنسانية.',
    category: 'Crisis Response',
    categoryAr: 'الاستجابة للأزمات',
    impact: '15,000+ families supported',
    impactAr: '15,000+ أسرة مدعومة',
    status: 'Active',
    objectives: ['Emergency relief provision', 'Medical assistance', 'Food security', 'Shelter support'],
    objectivesAr: ['توفير الإغاثة الطارئة', 'المساعدة الطبية', 'الأمن الغذائي', 'دعم المأوى'],
  },
  {
    id: 2,
    slug: 'amputees-gaza',
    name: 'Restoring Hope — Supporting Amputees in Gaza',
    nameAr: 'استعادة الأمل — دعم البتر في غزة',
    description: 'Prosthetic limbs, rehabilitation, and psychological support for amputees',
    descriptionAr: 'أطراف صناعية وإعادة تأهيل ودعم نفسي للبتر',
    longDescription: 'Specialized program providing prosthetic limbs, physical therapy, and psychological counseling to amputees in Gaza, restoring hope and enabling their return to productive lives.',
    longDescriptionAr: 'برنامج متخصص يوفر أطراف صناعية وعلاج فيزيائي واستشارات نفسية للبتر في غزة، مستعيداً الأمل وتمكين عودتهم للحياة المنتجة.',
    category: 'Healthcare',
    categoryAr: 'الرعاية الصحية',
    impact: '850+ amputees supported',
    impactAr: '850+ بتر مدعوم',
    status: 'Active',
    objectives: ['Prosthetic fitting', 'Physical rehabilitation', 'Mental health support', 'Social reintegration'],
    objectivesAr: ['تركيب أطراف صناعية', 'إعادة تأهيل بدني', 'دعم الصحة النفسية', 'إعادة الدمج الاجتماعي'],
  },
  {
    id: 3,
    slug: 'clothing-bank',
    name: 'Clothing Bank Initiative',
    nameAr: 'مبادرة بنك الملابس',
    description: 'Providing quality clothing to families in need across multiple regions',
    descriptionAr: 'توفير الملابس عالية الجودة للأسر المحتاجة عبر عدة مناطق',
    longDescription: 'Collecting and distributing quality clothing to vulnerable families, ensuring dignity and basic needs are met during challenging times.',
    longDescriptionAr: 'جمع وتوزيع الملابس عالية الجودة على الأسر الضعيفة، مما يضمن الكرامة وتلبية الاحتياجات الأساسية أثناء الأوقات الصعبة.',
    category: 'Basic Needs',
    categoryAr: 'الاحتياجات الأساسية',
    impact: '25,000+ people clothed',
    impactAr: '25,000+ شخص مُكسى',
    status: 'Active',
    objectives: ['Clothing collection', 'Distribution', 'Hygiene support', 'Dignity restoration'],
    objectivesAr: ['جمع الملابس', 'التوزيع', 'دعم النظافة', 'استعادة الكرامة'],
  },
  {
    id: 4,
    slug: 'education',
    name: 'Educational Support Program',
    nameAr: 'برنامج الدعم التعليمي',
    description: 'Scholarships and educational resources for underprivileged students',
    descriptionAr: 'منح وموارد تعليمية للطلاب المحرومين',
    longDescription: 'Providing scholarships, educational materials, and tutoring support to ensure every child has access to quality education regardless of economic circumstances.',
    longDescriptionAr: 'توفير المنح والمواد التعليمية ودعم الدروس الخصوصية لضمان حصول كل طفل على تعليم عالي الجودة بغض النظر عن الظروف الاقتصادية.',
    category: 'Education',
    categoryAr: 'التعليم',
    impact: '8,500+ students empowered',
    impactAr: '8,500+ طالب مُمكّن',
    status: 'Active',
    objectives: ['Scholarship provision', 'Learning materials', 'Tutoring support', 'School enrollment'],
    objectivesAr: ['توفير المنح', 'مواد التعلم', 'دعم الدروس', 'التحاق المدارس'],
  },
  {
    id: 5,
    slug: 'healthcare',
    name: 'Medical Clinics Network',
    nameAr: 'شبكة العيادات الطبية',
    description: 'Free healthcare services including checkups, medications, and surgeries',
    descriptionAr: 'خدمات طبية مجانية تشمل الفحوصات والأدوية والعمليات الجراحية',
    longDescription: 'Operating medical clinics across regions providing free healthcare services to ensure vulnerable populations have access to essential medical care.',
    longDescriptionAr: 'تشغيل عيادات طبية عبر المناطق توفير خدمات طبية مجانية لضمان حصول السكان الضعفاء على الرعاية الطبية الأساسية.',
    category: 'Healthcare',
    categoryAr: 'الرعاية الصحية',
    impact: '12,000+ treated annually',
    impactAr: '12,000+ مريض سنوياً',
    status: 'Active',
    objectives: ['Medical checkups', 'Medication provision', 'Surgical support', 'Health education'],
    objectivesAr: ['الفحوصات الطبية', 'توفير الأدوية', 'الدعم الجراحي', 'التثقيف الصحي'],
  },
  {
    id: 6,
    slug: 'livelihoods',
    name: 'Livelihood and Skills Training',
    nameAr: 'التدريب على سبل العيش والمهارات',
    description: 'Vocational training and income-generating activities for economic empowerment',
    descriptionAr: 'التدريب المهني والأنشطة المدرة للدخل للتمكين الاقتصادي',
    longDescription: 'Equipping individuals with vocational skills and supporting income-generating activities to achieve economic independence and sustainable livelihoods.',
    longDescriptionAr: 'تجهيز الأفراد بالمهارات المهنية ودعم الأنشطة المدرة للدخل لتحقيق الاستقلالية الاقتصادية وسبل العيش المستدامة.',
    category: 'Economic Empowerment',
    categoryAr: 'التمكين الاقتصادي',
    impact: '3,200+ trained',
    impactAr: '3,200+ مُدرّب',
    status: 'Active',
    objectives: ['Skills training', 'Job placement', 'Microfinance support', 'Business development'],
    objectivesAr: ['تدريب المهارات', 'التوظيف', 'دعم التمويل الأصغر', 'تطوير الأعمال'],
  },
  {
    id: 7,
    slug: 'food-security',
    name: 'Food Security Program',
    nameAr: 'برنامج الأمن الغذائي',
    description: 'Emergency food assistance and livelihood support ensuring nutritional dignity and sustainable food systems',
    descriptionAr: 'المساعدة الغذائية الطارئة ودعم سبل العيش لضمان الكرامة الغذائية والأنظمة الغذائية المستدامة',
    longDescription: 'The JHCO Food Security Program addresses hunger and malnutrition across vulnerable communities worldwide. We provide emergency food distribution, nutrition education, agricultural training, and livelihood support to build lasting food security. Our multi-faceted approach combines immediate relief with long-term sustainable solutions, empowering communities to achieve food independence.',
    longDescriptionAr: 'يعالج برنامج الأمن الغذائي بالهيئة الجوع وسوء التغذية عبر المجتمعات الضعيفة في جميع أنحاء العالم. نوفر توزيع الغذاء الطارئ والتثقيف الغذائي والتدريب الزراعي ودعم سبل العيش لبناء أمن غذائي دائم. يجمع نهجنا متعدد الأوجه بين الإغاثة الفورية والحلول المستدامة طويلة الأجل، مما يمكن المجتمعات من تحقيق الاستقلال الغذائي.',
    category: 'Food Security',
    categoryAr: 'الأمن الغذائي',
    impact: '125,000+ people served',
    impactAr: '125,000+ شخص مخدوم',
    status: 'Active',
    objectives: ['Emergency food distribution', 'Nutrition education', 'Agricultural training', 'Livelihood support', 'School feeding programs', 'Community sustainability'],
    objectivesAr: ['توزيع الغذاء الطارئ', 'التثقيف الغذائي', 'التدريب الزراعي', 'دعم سبل العيش', 'برامج التغذية المدرسية', 'استدامة المجتمع'],
  },
  {
    id: 8,
    slug: 'crisis-response-program',
    name: 'Crisis Response Program',
    nameAr: 'برنامج الاستجابة للأزمات',
    description: 'Comprehensive rapid-response initiatives providing humanitarian aid during emergencies and crises worldwide',
    descriptionAr: 'مبادرات استجابة سريعة شاملة توفر المساعدة الإنسانية أثناء الطوارئ والأزمات حول العالم',
    longDescription: 'JHCO\'s Crisis Response Program is a comprehensive, rapid-response initiative designed to provide immediate humanitarian assistance during emergencies and crises worldwide. We maintain constant readiness to deploy teams, resources, and expertise to affected regions within hours of a crisis occurrence. Our program integrates emergency relief distribution, medical support, shelter provision, and psychosocial assistance to address the multifaceted needs of affected populations. We work collaboratively with local partners and international organizations to maximize impact and ensure dignity in our response.',
    longDescriptionAr: 'برنامج الاستجابة للأزمات بالهيئة هو مبادرة استجابة سريعة شاملة مصممة لتوفير المساعدة الإنسانية الفورية أثناء الطوارئ والأزمات حول العالم. نحافظ على جاهزية مستمرة لنشر الفرق والموارد والخبرات للمناطق المتضررة في غضون ساعات من حدوث الأزمة. يدمج برنامجنا توزيع الإغاثة الطارئة والدعم الطبي وتوفير المأوى والمساعدة النفسية الاجتماعية لمعالجة الاحتياجات المتعددة الأوجه للسكان المتضررين. نعمل بشكل تعاوني مع الشركاء المحليين والمنظمات الدولية لتعظيم التأثير وضمان الكرامة في استجابتنا.',
    category: 'Crisis Response',
    categoryAr: 'الاستجابة للأزمات',
    impact: '150,000+ lives assisted',
    impactAr: '150,000+ حياة تم تقديم المساعدة لها',
    status: 'Active',
    objectives: [
      'Immediate emergency response deployment',
      'Food security and essential supplies distribution',
      'Medical assistance and healthcare services',
      'Shelter and temporary housing provision',
      'Psychosocial support and counseling',
      'Search and rescue operations',
      'Coordination with international humanitarian partners',
      'Post-crisis recovery and rehabilitation support'
    ],
    objectivesAr: [
      'نشر الاستجابة للطوارئ الفورية',
      'توزيع الأمن الغذائي والإمدادات الأساسية',
      'المساعدة الطبية وخدمات الرعاية الصحية',
      'توفير المأوى والإسكان المؤقت',
      'الدعم النفسي الاجتماعي والاستشارات',
      'عمليات البحث والإنقاذ',
      'التنسيق مع الشركاء الإنسانيين الدوليين',
      'دعم التعافي وإعادة التأهيل بعد الأزمة'
    ],
  },
];

export const newsAuthors = [
  {
    id: 1,
    name: 'Sarah Al-Rashid',
    nameAr: 'سارة الراشد',
    title: 'Communications Director',
    titleAr: 'مديرة الاتصالات',
    bio: 'Sarah leads JHCO\'s communications strategy with over 15 years of experience in humanitarian storytelling and digital media.',
    bioAr: 'تقود سارة استراتيجية الاتصالات بالهيئة بخبرة تزيد عن 15 سنة في السرد الإنساني ووسائل الإعلام الرقمية.',
    avatar: '👩‍💼',
  },
  {
    id: 2,
    name: 'Dr. Ahmed Al-Naimi',
    nameAr: 'د. أحمد النعيمي',
    title: 'Program Director',
    titleAr: 'مدير البرامج',
    bio: 'Dr. Ahmed oversees JHCO\'s humanitarian programs across 30+ countries with expertise in crisis management and sustainable development.',
    bioAr: 'يشرف د. أحمد على برامج الهيئة الإنسانية عبر 30+ دول بخبرة في إدارة الأزمات والتنمية المستدامة.',
    avatar: '👨‍⚕️',
  },
  {
    id: 3,
    name: 'Fatima Al-Suwaidi',
    nameAr: 'فاطمة السويدي',
    title: 'Field Operations Manager',
    titleAr: 'مديرة العمليات الميدانية',
    bio: 'Fatima brings a decade of field experience managing humanitarian operations in conflict zones and disaster areas.',
    bioAr: 'تجلب فاطمة عقداً من الخبرة الميدانية في إدارة العمليات الإنسانية في مناطق الصراع والمناطق المنكوبة.',
    avatar: '👩‍🔧',
  },
  {
    id: 4,
    name: 'Mohamed Al-Mansouri',
    nameAr: 'محمد المنصوري',
    title: 'Impact & Advocacy Lead',
    titleAr: 'قائد التأثير والدعوة',
    bio: 'Mohamed develops impact measurement strategies and advocates for vulnerable communities at international forums.',
    bioAr: 'يطور محمد استراتيجيات قياس التأثير ويدافع عن المجتمعات الضعيفة في المنتديات الدولية.',
    avatar: '👨‍💼',
  },
];

export const news = [
  {
    id: 1,
    slug: 'lebanon-aid-convoy',
    title: 'Jordan Dispatches Ninth Humanitarian Aid Convoy to Lebanon',
    titleAr: 'الأردن يرسل قافلة الإغاثة الإنسانية التاسعة إلى لبنان',
    excerpt: 'JHCO continues supporting Lebanon with a ninth humanitarian relief convoy',
    excerptAr: 'تواصل الهيئة دعم لبنان مع قافلة الإغاثة الإنسانية التاسعة',
    content: 'In a continued demonstration of solidarity with Lebanon, JHCO has dispatched its ninth humanitarian aid convoy to support families affected by the ongoing crisis. The convoy carries essential supplies including food items, medical equipment, blankets, and hygiene products. This initiative reflects JHCO\'s commitment to providing relief and hope to vulnerable populations.',
    contentAr: 'في إظهار مستمر للتضامن مع لبنان، أرسلت الهيئة قافلتها الإغاثية التاسعة لدعم الأسر المتضررة من الأزمة المستمرة. تحمل القافلة إمدادات أساسية تشمل المواد الغذائية والمعدات الطبية والبطاطين ومنتجات النظافة. تعكس هذه المبادرة التزام الهيئة بتقديم الإغاثة والأمل للفئات الضعيفة.',
    date: new Date('2026-08-02'),
    category: 'Crisis Response',
    categoryAr: 'الاستجابة للأزمات',
    author: 1,
    readTime: 5,
  },
  {
    id: 2,
    slug: 'bahrain-cooperation',
    title: 'JHCO and Bahrain Royal Charity Organisation Sign Historic Cooperation Agreement for Gaza',
    titleAr: 'الهيئة والمؤسسة الملكية للأعمال الخيرية توقعان اتفاقية تعاون تاريخية لغزة',
    excerpt: 'A new agreement to support those affected in the Gaza Strip through joint humanitarian efforts',
    excerptAr: 'اتفاق جديد لدعم المتضررين في قطاع غزة من خلال جهود إنسانية مشتركة',
    content: 'In a landmark development, JHCO has signed a comprehensive cooperation agreement with the Bahrain Royal Charity Organisation to provide large-scale humanitarian assistance to Gaza. The partnership aims to deliver emergency relief, medical support, food security, and livelihood programs to thousands of families affected by the crisis. This historic collaboration demonstrates the power of regional cooperation in humanitarian work.',
    contentAr: 'في تطور تاريخي، وقعت الهيئة اتفاقية تعاون شاملة مع مؤسسة البحرين الملكية للأعمال الخيرية لتقديم مساعدة إنسانية واسعة النطاق لغزة. تهدف الشراكة إلى تقديم الإغاثة الطارئة والدعم الطبي والأمن الغذائي وبرامج سبل العيش لآلاف الأسر المتضررة من الأزمة. يدل هذا التعاون التاريخي على قوة التعاون الإقليمي في العمل الإنساني.',
    date: new Date('2026-08-01'),
    category: 'Partnerships',
    categoryAr: 'الشراكات',
    author: 2,
    readTime: 6,
  },
  {
    id: 3,
    slug: 'education-initiative',
    title: 'Educational Support Program Reaches 8,500 Students Milestone',
    titleAr: 'برنامج الدعم التعليمي يحقق إنجازاً بـ 8,500 طالب',
    excerpt: 'Celebrating a major milestone achievement in educational empowerment across 15 countries',
    excerptAr: 'الاحتفال بإنجاز كبير في التمكين التعليمي عبر 15 دول',
    content: 'JHCO proudly announces that its Educational Support Program has reached a significant milestone by supporting 8,500 students across 15 countries. Through scholarships, learning materials, and mentorship programs, the initiative has transformed educational opportunities for vulnerable youth. Students have reported improved academic performance and increased confidence in their futures.',
    contentAr: 'تعلن الهيئة بفخر أن برنامج الدعم التعليمي قد حقق مرحلة فاصلة بدعم 8,500 طالب عبر 15 دول. من خلال المنح والمواد التعليمية وبرامج الإرشاد، حولت المبادرة الفرص التعليمية للشباب الضعيف. أفاد الطلاب بتحسن الأداء الأكاديمي وزيادة الثقة في مستقبلهم.',
    date: new Date('2026-07-28'),
    category: 'Education',
    categoryAr: 'التعليم',
    author: 3,
    readTime: 5,
  },
  {
    id: 4,
    slug: 'food-security-gaza',
    title: 'Emergency Food Distribution Program Begins in Gaza',
    titleAr: 'برنامج توزيع الغذاء الطارئ يبدأ في غزة',
    excerpt: 'JHCO launches comprehensive food security initiative supporting 10,000 families with essential nutrition',
    excerptAr: 'تطلق الهيئة مبادرة شاملة للأمن الغذائي تدعم 10,000 أسرة بالتغذية الأساسية',
    content: 'JHCO has launched an emergency food distribution program in Gaza to address acute food insecurity. Working with local partners, the program delivers nutritious food baskets to 10,000 families in the most vulnerable areas. The initiative includes nutritional assessment, dietary counseling, and sustainable livelihood support to ensure long-term food security.',
    contentAr: 'أطلقت الهيئة برنامج توزيع غذاء طارئ في غزة لمعالجة انعدام الأمن الغذائي الحاد. بالعمل مع الشركاء المحليين، يوفر البرنامج سلات غذائية مغذية لـ 10,000 أسرة في المناطق الأكثر ضعفاً. تشمل المبادرة تقييم التغذية والاستشارات الغذائية ودعم سبل العيش المستدامة لضمان الأمن الغذائي طويل الأجل.',
    date: new Date('2026-07-25'),
    category: 'Food Security',
    categoryAr: 'الأمن الغذائي',
    author: 4,
    readTime: 7,
  },
  {
    id: 5,
    slug: 'healthcare-expansion',
    title: 'JHCO Expands Healthcare Services with Three New Medical Clinics',
    titleAr: 'الهيئة توسع الخدمات الصحية بثلاث عيادات طبية جديدة',
    excerpt: 'New healthcare facilities bring essential medical services closer to underserved communities',
    excerptAr: 'منشآت صحية جديدة تقرب الخدمات الطبية الأساسية من المجتمعات المحرومة',
    content: 'JHCO has inaugurated three new medical clinics in strategic locations to expand healthcare access. These facilities provide free consultations, medications, minor surgeries, and maternal healthcare services. The clinics are staffed by qualified doctors and nurses, ensuring quality care for vulnerable populations. Early reports indicate high patient satisfaction and improved health outcomes.',
    contentAr: 'افتتحت الهيئة ثلاث عيادات طبية جديدة في مواقع استراتيجية لتوسيع الوصول إلى الرعاية الصحية. توفر هذه المنشآت استشارات مجانية والأدوية والعمليات الجراحية البسيطة وخدمات الرعاية قبل الولادة. تديرها أطباء وممرضات مؤهلون، مما يضمن رعاية عالية الجودة للفئات الضعيفة. تشير التقارير الأولية إلى رضا عالي للمرضى وتحسن النتائج الصحية.',
    date: new Date('2026-07-20'),
    category: 'Healthcare',
    categoryAr: 'الرعاية الصحية',
    author: 2,
    readTime: 6,
  },
  {
    id: 6,
    slug: 'women-empowerment-wins',
    title: 'Women Empowerment Program Celebrates Business Success Stories',
    titleAr: 'برنامج تمكين المرأة يحتفي بقصص نجاح الأعمال',
    excerpt: '3,500 women entrepreneurs have launched successful small businesses through JHCO support',
    excerptAr: '3,500 رائدة أعمال أطلقن مشاريع صغيرة ناجحة من خلال دعم الهيئة',
    content: 'The Women Empowerment and Leadership Program celebrates remarkable success as 3,500 women have launched their own businesses. These entrepreneurs received business training, microfinance support, and ongoing mentorship. Their enterprises span agriculture, retail, crafts, and services sectors, creating employment for their families and communities. Average business revenue has grown by 150% within the first two years.',
    contentAr: 'يحتفي برنامج تمكين النساء والقيادة بنجاح ملحوظ حيث أطلقت 3,500 امرأة مشاريعهن الخاصة. تلقت رائدات الأعمال هذه تدريباً على الأعمال ودعماً بالتمويل الأصغر وإرشاداً مستمراً. تمتد مشاريعهن إلى قطاعات الزراعة والبيع بالتجزئة والحرف والخدمات، مما يخلق فرص عمل لأسرهن ومجتمعاتهن. نما متوسط إيراد الأعمال بنسبة 150% خلال السنتين الأوليين.',
    date: new Date('2026-07-15'),
    category: 'Empowerment',
    categoryAr: 'التمكين',
    author: 1,
    readTime: 8,
  },
  {
    id: 7,
    slug: 'youth-skills-training',
    title: 'Youth Skills Initiative Transforms 2,000 Lives with Vocational Training',
    titleAr: 'مبادرة مهارات الشباب تغير 2,000 حياة من خلال التدريب المهني',
    excerpt: 'Young people gain employment readiness through comprehensive vocational training programs',
    excerptAr: 'يكتسب الشباب القابلية للتوظيف من خلال برامج تدريب مهني شاملة',
    content: 'The Royal Youth Development Initiative has successfully trained 2,000 young people in high-demand vocational skills including plumbing, electrical work, carpentry, and digital marketing. With 85% job placement rate post-training, participants report significant income increases and improved quality of life. The program also provides internship opportunities and ongoing career support.',
    contentAr: 'دربت مبادرة تطوير الشباب الملكية بنجاح 2,000 شاب في مهارات مهنية عالية الطلب تشمل السباكة والأعمال الكهربائية النجارة والتسويق الرقمي. مع معدل توظيف بنسبة 85% بعد التدريب، يُبلغ المشاركون عن زيادات دخل كبيرة وتحسن جودة الحياة. يوفر البرنامج أيضاً فرص تدريب داخلي ودعم وظيفي مستمر.',
    date: new Date('2026-07-10'),
    category: 'Youth Programs',
    categoryAr: 'برامج الشباب',
    author: 3,
    readTime: 7,
  },
  {
    id: 8,
    slug: 'refugee-support-turkey',
    title: 'Supporting Syrian Refugees: JHCO\'s Comprehensive Assistance Program in Turkey',
    titleAr: 'دعم اللاجئين السوريين: برنامج الدعم الشامل للهيئة في تركيا',
    excerpt: 'Providing shelter, education, healthcare, and livelihood support to 38,000 Syrian refugees',
    excerptAr: 'توفير المأوى والتعليم والرعاية الصحية ودعم سبل العيش لـ 38,000 لاجئ سوري',
    content: 'JHCO operates one of the largest refugee support programs in Turkey, assisting 38,000 Syrian refugees. Services include emergency shelter, WASH facilities, healthcare clinics, educational programs for children, and vocational training for adults. The program emphasizes dignity, cultural sensitivity, and integration support, helping refugees rebuild their lives with hope and security.',
    contentAr: 'تدير الهيئة أحد أكبر برامج دعم اللاجئين في تركيا، تساعد 38,000 لاجئ سوري. تشمل الخدمات المأوى الطارئ ومرافق المياه والصرف الصحي والعيادات الصحية والبرامج التعليمية للأطفال والتدريب المهني للبالغين. يركز البرنامج على الكرامة والحساسية الثقافية ودعم الاندماج، مما يساعد اللاجئين على إعادة بناء حياتهم بأمل وأمان.',
    date: new Date('2026-07-05'),
    category: 'Refugee Support',
    categoryAr: 'دعم اللاجئين',
    author: 4,
    readTime: 8,
  },
  {
    id: 9,
    slug: 'disaster-relief-success',
    title: 'Flood Relief Operations Save Lives in Multiple Countries',
    titleAr: 'عمليات الإغاثة من الفيضانات إنقاذ الأرواح في عدة دول',
    excerpt: 'JHCO\'s rapid response teams deliver aid to 15,000 families affected by devastating floods',
    excerptAr: 'فرق الاستجابة السريعة بالهيئة توصل المساعدات إلى 15,000 أسرة متضررة من الفيضانات المدمرة',
    content: 'Following severe flooding across multiple regions, JHCO mobilized rapid-response teams to deliver emergency relief within 48 hours. Over 15,000 families received food packages, clean water, medical care, and emergency shelter. The swift action prevented disease outbreaks and secondary crises. JHCO\'s disaster preparedness training in communities proved invaluable in minimizing casualties.',
    contentAr: 'بعد فيضانات شديدة عبر عدة مناطق، حشدت الهيئة فرق الاستجابة السريعة لتقديم الإغاثة الطارئة في غضون 48 ساعة. تلقت أكثر من 15,000 أسرة حزم غذائية ومياه نظيفة رعاية طبية ومأوى طارئ. منع الإجراء السريع تفشي الأمراض والأزمات الثانوية. أثبت تدريب استعداد الكوارث بالهيئة في المجتمعات فائدة لا تقدر بثمن في تقليل الوفيات.',
    date: new Date('2026-06-30'),
    category: 'Disaster Relief',
    categoryAr: 'إغاثة الكوارث',
    author: 2,
    readTime: 6,
  },
  {
    id: 10,
    slug: 'collaboration-announcement',
    title: 'JHCO Launches New International Humanitarian Alliance',
    titleAr: 'الهيئة تطلق تحالفاً إنسانياً دولياً جديداً',
    excerpt: 'Strategic collaboration with 12 international organizations to strengthen global humanitarian response',
    excerptAr: 'تعاون استراتيجي مع 12 منظمة دولية لتعزيز الاستجابة الإنسانية العالمية',
    content: 'JHCO has established the International Humanitarian Alliance, bringing together 12 major international organizations to coordinate humanitarian efforts. This collaboration will enhance resource sharing, improve response coordination, reduce operational duplication, and amplify impact. The alliance will focus on crisis response, disaster preparedness, and sustainable development across 50+ countries.',
    contentAr: 'أنشأت الهيئة التحالف الإنساني الدولي، الذي جمع 12 منظمة دولية رئيسية لتنسيق الجهود الإنسانية. سيعزز هذا التعاون مشاركة الموارد وتحسين تنسيق الاستجابة وتقليل ازدواجية العمليات وتضخيم التأثير. سيركز التحالف على الاستجابة للأزمات والاستعداد للكوارث والتنمية المستدامة عبر 50+ دول.',
    date: new Date('2026-06-25'),
    category: 'Partnerships',
    categoryAr: 'الشراكات',
    author: 1,
    readTime: 7,
  },
  {
    id: 11,
    slug: 'mental-health-initiative',
    title: 'Launching Comprehensive Mental Health Support for Crisis-Affected Communities',
    titleAr: 'إطلاق برنامج شامل للصحة النفسية للمجتمعات المتضررة من الأزمات',
    excerpt: 'JHCO introduces psychological counseling and trauma support services across affected regions',
    excerptAr: 'تقدم الهيئة خدمات الاستشارة النفسية ودعم الصدمات عبر المناطق المتضررة',
    content: 'Recognizing the invisible wounds of crisis, JHCO has launched a comprehensive mental health initiative providing psychological counseling, trauma therapy, and psychosocial support to survivors. Trained mental health professionals work with communities to address anxiety, depression, PTSD, and grief. The program includes support groups, awareness campaigns, and integration with medical services.',
    contentAr: 'إدراكاً للجروح غير المرئية للأزمات، أطلقت الهيئة مبادرة شاملة للصحة النفسية توفر الاستشارة النفسية والعلاج النفسي ودعم نفسي اجتماعي للناجين. يعمل متخصصو الصحة النفسية المدربون مع المجتمعات لمعالجة القلق والاكتئاب واضطراب ما بعد الصدمة والحزن. يشمل البرنامج مجموعات دعم وحملات توعية والتكامل مع الخدمات الطبية.',
    date: new Date('2026-06-20'),
    category: 'Mental Health',
    categoryAr: 'الصحة النفسية',
    author: 3,
    readTime: 8,
  },
  {
    id: 12,
    slug: 'water-sanitation-project',
    title: 'JHCO Completes Water and Sanitation Project Serving 50,000 People',
    titleAr: 'الهيئة تكمل مشروع المياه والصرف الصحي الخدمة 50,000 شخص',
    excerpt: 'Safe water access and improved sanitation facilities transform lives in underserved communities',
    excerptAr: 'الوصول إلى مياه آمنة ومرافق صرف صحي محسنة تحول الحياة في المجتمعات المحرومة',
    content: 'JHCO has successfully completed a major water and sanitation infrastructure project, providing safe drinking water and proper sanitation facilities to 50,000 people in six countries. The project included construction of water wells, installation of filtration systems, and building of hygiene facilities. Community training on water conservation and health practices ensures long-term sustainability.',
    contentAr: 'أكملت الهيئة بنجاح مشروع بنية تحتية كبيرة للمياه والصرف الصحي، توفير المياه الصالحة للشرب ومرافق الصرف الصحي المناسبة لـ 50,000 شخص في ست دول. تضمن المشروع حفر آبار المياه وتركيب أنظمة الترشيح وبناء مرافق النظافة. يضمن التدريب المجتمعي على حفظ المياه والممارسات الصحية الاستدامة طويلة الأجل.',
    date: new Date('2026-06-15'),
    category: 'Infrastructure',
    categoryAr: 'البنية التحتية',
    author: 4,
    readTime: 7,
  },
  {
    id: 13,
    slug: 'volunteer-recognition',
    title: 'Celebrating 2,500 Dedicated Volunteers: Recognition and Impact Stories',
    titleAr: 'الاحتفال بـ 2,500 متطوع مكرس: قصص الاعتراف والتأثير',
    excerpt: 'Honoring our volunteers whose selfless service transforms humanitarian work on the ground',
    excerptAr: 'تكريم المتطوعين الذين يحول عملهم الإيثاري العمل الإنساني على الأرض',
    content: 'JHCO celebrates the remarkable contributions of 2,500 active volunteers who dedicate their time and energy to humanitarian missions. From healthcare workers to logisticians, educators to community mobilizers, these volunteers embody the spirit of compassion and service. Their stories of impact demonstrate how individual commitment creates collective change and saves lives.',
    contentAr: 'تحتفي الهيئة بالمساهمات الملحوظة لـ 2,500 متطوع نشط يكرسون وقتهم وطاقتهم للمهام الإنسانية. من العاملين الصحيين إلى اللوجستيين والمعلمين إلى منظمي المجتمعات، يجسد هؤلاء المتطوعون روح الرحمة والخدمة. تُظهر قصصهم عن التأثير كيف يخلق الالتزام الفردي تغييراً جماعياً وإنقاذ الأرواح.',
    date: new Date('2026-06-10'),
    category: 'Volunteers',
    categoryAr: 'المتطوعون',
    author: 1,
    readTime: 6,
  },
  {
    id: 14,
    slug: 'environmental-sustainability',
    title: 'Green Initiatives: JHCO\'s Environmental Sustainability and Climate Action Programs',
    titleAr: 'المبادرات الخضراء: برامج الاستدامة البيئية والعمل المناخي للهيئة',
    excerpt: 'Integrating environmental protection with humanitarian work to build sustainable communities',
    excerptAr: 'دمج الحماية البيئية مع العمل الإنساني لبناء مجتمعات مستدامة',
    content: 'JHCO launches integrated environmental sustainability programs combining disaster prevention, renewable energy deployment, and ecosystem restoration. These initiatives aim to reduce climate vulnerability in humanitarian contexts while creating green employment opportunities. Community-based conservation efforts in six countries demonstrate how environmental stewardship enhances food security and resilience.',
    contentAr: 'تطلق الهيئة برامج استدامة بيئية متكاملة تجمع بين منع الكوارث ونشر الطاقة المتجددة واستعادة النظم البيئية. تهدف هذه المبادرات إلى تقليل الضعف المناخي في السياقات الإنسانية مع خلق فرص عمل خضراء. تُظهر جهود الحفاظ على المستوى المجتمعي في ست دول كيف يعزز التنمية البيئية الأمن الغذائي والمرونة.',
    date: new Date('2026-06-05'),
    category: 'Sustainability',
    categoryAr: 'الاستدامة',
    author: 2,
    readTime: 9,
  },
  {
    id: 15,
    slug: 'technology-impact',
    title: 'Digital Innovation: How Technology Amplifies JHCO\'s Humanitarian Reach',
    titleAr: 'الابتكار الرقمي: كيف تعزز التكنولوجيا نطاق الهيئة الإنساني',
    excerpt: 'Mobile apps, digital platforms, and data analytics improve program delivery and impact measurement',
    excerptAr: 'تطبيقات الهاتف المحمول والمنصات الرقمية وتحليلات البيانات تحسن تقديم البرامج وقياس التأثير',
    content: 'JHCO leverages cutting-edge technology to enhance humanitarian operations. Mobile apps enable beneficiary registration and tracking, digital platforms connect volunteers with opportunities, and advanced analytics measure program outcomes. Cloud-based systems ensure real-time coordination across 30+ countries. Investments in technology infrastructure demonstrate our commitment to operational excellence and data-driven decision making.',
    contentAr: 'تستفيد الهيئة من أحدث التقنيات لتعزيز العمليات الإنسانية. تتيح تطبيقات الهاتف المحمول تسجيل المستفيدين والتتبع، والمنصات الرقمية تربط المتطوعين بالفرص، وتحليلات متقدمة تقيس نتائج البرامج. تضمن الأنظمة المستندة إلى السحابة التنسيق في الوقت الفعلي عبر 30+ دول. تُظهر الاستثمارات في البنية التحتية التكنولوجية التزامنا بالتميز التشغيلي واتخاذ القرارات المستندة إلى البيانات.',
    date: new Date('2026-06-01'),
    category: 'Innovation',
    categoryAr: 'الابتكار',
    author: 3,
    readTime: 8,
  },
];

// Geographic Data - Regions and Countries
export const regions = [
  {
    id: 1,
    slug: 'asia',
    name: 'Asia',
    nameAr: 'آسيا',
    description: 'JHCO operates across 17 countries in Asia, providing humanitarian aid and development support to vulnerable populations across the continent.',
    descriptionAr: 'تعمل الهيئة عبر 17 دولة في آسيا، توفر المساعدات الإنسانية والدعم التنموي للفئات الضعيفة عبر القارة.',
    countries: ['afghanistan', 'bangladesh', 'china', 'georgia', 'indonesia', 'iran', 'iraq', 'japan', 'lebanon', 'palestine', 'pakistan', 'philippines', 'sri-lanka', 'syria', 'taiwan', 'thailand', 'turkey'],
  },
  {
    id: 2,
    slug: 'africa',
    name: 'Africa',
    nameAr: 'أفريقيا',
    description: 'JHCO supports 10 African nations with crisis response, healthcare, education, and livelihood programs to build sustainable development.',
    descriptionAr: 'تدعم الهيئة 10 دول أفريقية ببرامج الاستجابة للأزمات والرعاية الصحية والتعليم وسبل العيش لبناء تنمية مستدامة.',
    countries: ['algeria', 'comoros', 'congo', 'egypt', 'ivory-coast', 'liberia', 'libya', 'morocco', 'somalia', 'sudan'],
  },
  {
    id: 3,
    slug: 'europe',
    name: 'Europe',
    nameAr: 'أوروبا',
    description: 'JHCO operates in 7 European countries, focusing on crisis response and humanitarian assistance to vulnerable communities.',
    descriptionAr: 'تعمل الهيئة في 7 دول أوروبية، مركزة على الاستجابة للأزمات والمساعدة الإنسانية للمجتمعات الضعيفة.',
    countries: ['abkhazia', 'bosnia', 'bulgaria', 'chechnya', 'macedonia', 'romania', 'south-ossetia'],
  },
  {
    id: 4,
    slug: 'americas',
    name: 'Americas',
    nameAr: 'الأمريكتان',
    description: 'JHCO extends its humanitarian reach to the Americas, with special focus on emergency response and community development.',
    descriptionAr: 'تمد الهيئة نطاق عملها الإنساني ليشمل الأمريكتان، مع التركيز على الاستجابة للطوارئ وتنمية المجتمع.',
    countries: ['haiti'],
  },
  {
    id: 5,
    slug: 'middle-east',
    name: 'Middle East',
    nameAr: 'الشرق الأوسط',
    description: 'JHCO operates across 5 strategic countries in the Middle East and North Africa region, providing comprehensive humanitarian assistance, crisis response, healthcare, education, and livelihood programs to vulnerable populations.',
    descriptionAr: 'تعمل الهيئة عبر 5 دول استراتيجية في منطقة الشرق الأوسط وشمال أفريقيا، توفر مساعدات إنسانية شاملة واستجابة للأزمات والرعاية الصحية والتعليم وبرامج سبل العيش للفئات الضعيفة.',
    countries: ['jordan', 'lebanon', 'syria', 'palestine', 'iraq'],
  },
];

export const countries = [
  // ASIA
  {
    id: 1,
    slug: 'afghanistan',
    name: 'Afghanistan',
    nameAr: 'أفغانستان',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇦🇫',
    programs: ['Healthcare', 'Education', 'Food Security', 'Livelihoods'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'الأمن الغذائي', 'سبل العيش'],
    impact: '12,000+ families supported',
    impactAr: '12,000+ أسرة مدعومة',
    description: 'JHCO operates medical clinics and educational programs across Afghanistan, providing essential healthcare and scholarship support to vulnerable communities.',
    descriptionAr: 'تعمل الهيئة على تشغيل عيادات طبية وبرامج تعليمية في أفغانستان، توفر الرعاية الصحية الأساسية والدعم المنح الدراسية للمجتمعات الضعيفة.',
    office: 'Kabul Regional Office',
    officeAr: 'مكتب كابول الإقليمي',
  },
  {
    id: 2,
    slug: 'bangladesh',
    name: 'Bangladesh',
    nameAr: 'بنغلاديش',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇧🇩',
    programs: ['Healthcare', 'Education', 'Livelihood Training', 'Women Empowerment'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش', 'تمكين النساء'],
    impact: '8,500+ individuals trained',
    impactAr: '8,500+ فرد مُدرّب',
    description: 'Active programs in healthcare delivery and vocational training, empowering women and youth in rural communities.',
    descriptionAr: 'برامج نشطة في توفير الرعاية الصحية والتدريب المهني، تمكين النساء والشباب في المجتمعات الريفية.',
    office: 'Dhaka Coordination Center',
    officeAr: 'مركز داكا التنسيقي',
  },
  {
    id: 3,
    slug: 'china',
    name: 'China',
    nameAr: 'الصين',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇨🇳',
    programs: ['Education', 'Healthcare'],
    programsAr: ['التعليم', 'الرعاية الصحية'],
    impact: '3,200+ students supported',
    impactAr: '3,200+ طالب مدعوم',
    description: 'Educational scholarships and healthcare initiatives supporting vulnerable populations in rural regions.',
    descriptionAr: 'منح دراسية ومبادرات الرعاية الصحية تدعم الفئات الضعيفة في المناطق الريفية.',
    office: 'Beijing Office',
    officeAr: 'مكتب بكين',
  },
  {
    id: 4,
    slug: 'georgia',
    name: 'Georgia',
    nameAr: 'جورجيا',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇬🇪',
    programs: ['Crisis Response', 'Healthcare', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي'],
    impact: '6,500+ crisis-affected supported',
    impactAr: '6,500+ متضرر من الأزمات مدعوم',
    description: 'Emergency humanitarian assistance to conflict-affected communities, including food distribution and medical support.',
    descriptionAr: 'مساعدة إنسانية طارئة للمجتمعات المتأثرة بالصراعات، بما فيها توزيع الغذاء والدعم الطبي.',
    office: 'Tbilisi Humanitarian Hub',
    officeAr: 'مركز تبليسي الإنساني',
  },
  {
    id: 5,
    slug: 'indonesia',
    name: 'Indonesia',
    nameAr: 'إندونيسيا',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇮🇩',
    programs: ['Disaster Relief', 'Healthcare', 'Education'],
    programsAr: ['إغاثة الكوارث', 'الرعاية الصحية', 'التعليم'],
    impact: '45,000+ disaster-affected supported',
    impactAr: '45,000+ متضرر من الكوارث مدعوم',
    description: 'Disaster response operations and ongoing health and education programs for vulnerable communities.',
    descriptionAr: 'عمليات الاستجابة للكوارث وبرامج الصحة والتعليم المستمرة للمجتمعات الضعيفة.',
    office: 'Jakarta Emergency Operations',
    officeAr: 'عمليات جاكرتا الطارئة',
  },
  {
    id: 6,
    slug: 'iran',
    name: 'Iran',
    nameAr: 'إيران',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇮🇷',
    programs: ['Healthcare', 'Livelihood Support'],
    programsAr: ['الرعاية الصحية', 'دعم سبل العيش'],
    impact: '5,200+ individuals served',
    impactAr: '5,200+ فرد مخدوم',
    description: 'Medical clinics and economic empowerment initiatives supporting vulnerable populations.',
    descriptionAr: 'عيادات طبية ومبادرات التمكين الاقتصادي تدعم الفئات الضعيفة.',
    office: 'Tehran Operations Office',
    officeAr: 'مكتب طهران التشغيلي',
  },
  {
    id: 7,
    slug: 'iraq',
    name: 'Iraq',
    nameAr: 'العراق',
    region: 'middle-east',
    regionAr: 'الشرق الأوسط',
    flag: '🇮🇶',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم'],
    impact: '28,000+ crisis-affected supported',
    impactAr: '28,000+ متضرر من الأزمات مدعوم',
    description: 'Comprehensive humanitarian response including emergency aid, medical support, food distribution, and educational programs.',
    descriptionAr: 'استجابة إنسانية شاملة تشمل المساعدات الطارئة والدعم الطبي وتوزيع الغذاء والبرامج التعليمية.',
    office: 'Baghdad Central Hub',
    officeAr: 'مركز بغداد المركزي',
  },
  {
    id: 8,
    slug: 'japan',
    name: 'Japan',
    nameAr: 'اليابان',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇯🇵',
    programs: ['Education', 'Community Support'],
    programsAr: ['التعليم', 'دعم المجتمع'],
    impact: '2,500+ beneficiaries',
    impactAr: '2,500+ مستفيد',
    description: 'Educational programs and community development initiatives supporting international cooperation.',
    descriptionAr: 'برامج تعليمية ومبادرات تنمية المجتمع تدعم التعاون الدولي.',
    office: 'Tokyo Coordination Office',
    officeAr: 'مكتب طوكيو التنسيقي',
  },
  {
    id: 9,
    slug: 'lebanon',
    name: 'Lebanon',
    nameAr: 'لبنان',
    region: 'middle-east',
    regionAr: 'الشرق الأوسط',
    flag: '🇱🇧',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education', 'Livelihoods'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم', 'سبل العيش'],
    impact: '35,000+ families supported',
    impactAr: '35,000+ أسرة مدعومة',
    description: 'Major operations center with comprehensive humanitarian programs addressing refugee needs, healthcare, education, and economic empowerment.',
    descriptionAr: 'مركز عمليات رئيسي ببرامج إنسانية شاملة تعالج احتياجات اللاجئين والرعاية الصحية والتعليم والتمكين الاقتصادي.',
    office: 'Beirut Regional Headquarters',
    officeAr: 'مقر بيروت الإقليمي',
  },
  {
    id: 10,
    slug: 'palestine',
    name: 'Palestine',
    nameAr: 'فلسطين',
    region: 'middle-east',
    regionAr: 'الشرق الأوسط',
    flag: '🇵🇸',
    programs: ['Crisis Response', 'Healthcare', 'Education', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'التعليم', 'الأمن الغذائي'],
    impact: '32,000+ people supported',
    impactAr: '32,000+ شخص مدعوم',
    description: 'Emergency humanitarian assistance, medical services, educational support, and food distribution to vulnerable populations.',
    descriptionAr: 'مساعدة إنسانية طارئة وخدمات طبية ودعم تعليمي وتوزيع غذاء للفئات الضعيفة.',
    office: 'Gaza & West Bank Operations',
    officeAr: 'عمليات غزة والضفة الغربية',
  },
  {
    id: 11,
    slug: 'pakistan',
    name: 'Pakistan',
    nameAr: 'باكستان',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇵🇰',
    programs: ['Disaster Relief', 'Healthcare', 'Education', 'Livelihoods'],
    programsAr: ['إغاثة الكوارث', 'الرعاية الصحية', 'التعليم', 'سبل العيش'],
    impact: '22,000+ beneficiaries',
    impactAr: '22,000+ مستفيد',
    description: 'Flood and disaster relief operations, healthcare clinics, education programs, and vocational training initiatives.',
    descriptionAr: 'عمليات إغاثة الفيضانات والكوارث، عيادات الرعاية الصحية، برامج التعليم، ومبادرات التدريب المهني.',
    office: 'Islamabad Humanitarian Center',
    officeAr: 'مركز إسلام أباد الإنساني',
  },
  {
    id: 12,
    slug: 'philippines',
    name: 'Philippines',
    nameAr: 'الفلبين',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇵🇭',
    programs: ['Disaster Relief', 'Healthcare', 'Livelihood Training'],
    programsAr: ['إغاثة الكوارث', 'الرعاية الصحية', 'تدريب سبل العيش'],
    impact: '18,000+ typhoon survivors assisted',
    impactAr: '18,000+ ناجي من الأعاصير مساعدة',
    description: 'Typhoon disaster response, medical services, and economic empowerment programs for affected communities.',
    descriptionAr: 'استجابة لكوارث الأعاصير، خدمات طبية، وبرامج التمكين الاقتصادي للمجتمعات المتأثرة.',
    office: 'Manila Operations Center',
    officeAr: 'مركز مانيلا التشغيلي',
  },
  {
    id: 13,
    slug: 'sri-lanka',
    name: 'Sri Lanka',
    nameAr: 'سري لانكا',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇱🇰',
    programs: ['Healthcare', 'Education', 'Livelihood Support'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'دعم سبل العيش'],
    impact: '7,500+ beneficiaries',
    impactAr: '7,500+ مستفيد',
    description: 'Healthcare delivery, educational scholarships, and income-generating activity support.',
    descriptionAr: 'توصيل الرعاية الصحية والمنح الدراسية ودعم الأنشطة المدرة للدخل.',
    office: 'Colombo Regional Office',
    officeAr: 'مكتب كولومبو الإقليمي',
  },
  {
    id: 14,
    slug: 'syria',
    name: 'Syria',
    nameAr: 'سوريا',
    region: 'middle-east',
    regionAr: 'الشرق الأوسط',
    flag: '🇸🇾',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم'],
    impact: '55,000+ crisis-affected supported',
    impactAr: '55,000+ متضرر من الأزمات مدعوم',
    description: 'Large-scale humanitarian response including emergency relief, healthcare, food assistance, and educational support.',
    descriptionAr: 'استجابة إنسانية واسعة النطاق تشمل الإغاثة الطارئة والرعاية الصحية والمساعدة الغذائية والدعم التعليمي.',
    office: 'Damascus Crisis Response Hub',
    officeAr: 'مركز دمشق للاستجابة للأزمات',
  },
  {
    id: 15,
    slug: 'taiwan',
    name: 'Taiwan',
    nameAr: 'تايوان',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇹🇼',
    programs: ['Education', 'Community Development'],
    programsAr: ['التعليم', 'تنمية المجتمع'],
    impact: '3,000+ students supported',
    impactAr: '3,000+ طالب مدعوم',
    description: 'Educational programs and community development initiatives supporting vulnerable populations.',
    descriptionAr: 'برامج تعليمية ومبادرات تنمية المجتمع تدعم الفئات الضعيفة.',
    office: 'Taipei Coordination Office',
    officeAr: 'مكتب تايبيه التنسيقي',
  },
  {
    id: 16,
    slug: 'thailand',
    name: 'Thailand',
    nameAr: 'تايلاند',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇹🇭',
    programs: ['Healthcare', 'Education', 'Livelihood Training'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش'],
    impact: '9,000+ individuals served',
    impactAr: '9,000+ فرد مخدوم',
    description: 'Medical clinics, educational scholarships, and vocational training supporting vulnerable communities.',
    descriptionAr: 'عيادات طبية ومنح دراسية وتدريب مهني يدعم المجتمعات الضعيفة.',
    office: 'Bangkok Operations Office',
    officeAr: 'مكتب بانكوك التشغيلي',
  },
  {
    id: 17,
    slug: 'turkey',
    name: 'Turkey',
    nameAr: 'تركيا',
    region: 'asia',
    regionAr: 'آسيا',
    flag: '🇹🇷',
    programs: ['Refugee Support', 'Healthcare', 'Education', 'Food Security'],
    programsAr: ['دعم اللاجئين', 'الرعاية الصحية', 'التعليم', 'الأمن الغذائي'],
    impact: '38,000+ Syrian refugees supported',
    impactAr: '38,000+ لاجئ سوري مدعوم',
    description: 'Comprehensive refugee support programs including shelter, healthcare, education, and livelihood assistance.',
    descriptionAr: 'برامج دعم اللاجئين الشاملة تشمل المأوى والرعاية الصحية والتعليم ودعم سبل العيش.',
    office: 'Istanbul Regional Hub',
    officeAr: 'مركز اسطنبول الإقليمي',
  },

  // AFRICA
  {
    id: 18,
    slug: 'algeria',
    name: 'Algeria',
    nameAr: 'الجزائر',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇩🇿',
    programs: ['Healthcare', 'Education', 'Food Security'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'الأمن الغذائي'],
    impact: '8,500+ families supported',
    impactAr: '8,500+ أسرة مدعومة',
    description: 'Healthcare clinics, educational programs, and food assistance for vulnerable populations.',
    descriptionAr: 'عيادات الرعاية الصحية والبرامج التعليمية والمساعدة الغذائية للفئات الضعيفة.',
    office: 'Algiers Regional Office',
    officeAr: 'مكتب الجزائر الإقليمي',
  },
  {
    id: 19,
    slug: 'comoros',
    name: 'Comoros Islands',
    nameAr: 'جزر القمر',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇰🇲',
    programs: ['Healthcare', 'Education', 'Disaster Relief'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'إغاثة الكوارث'],
    impact: '3,200+ beneficiaries',
    impactAr: '3,200+ مستفيد',
    description: 'Island-based medical and educational programs supporting isolated communities.',
    descriptionAr: 'برامج طبية وتعليمية قائمة على الجزر تدعم المجتمعات المعزولة.',
    office: 'Moroni Operations Center',
    officeAr: 'مركز موروني التشغيلي',
  },
  {
    id: 20,
    slug: 'congo',
    name: 'Congo',
    nameAr: 'الكونغو',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇨🇬',
    programs: ['Crisis Response', 'Healthcare', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'التعليم'],
    impact: '12,000+ crisis-affected supported',
    impactAr: '12,000+ متضرر من الأزمات مدعوم',
    description: 'Emergency humanitarian assistance and ongoing healthcare and education programs.',
    descriptionAr: 'مساعدة إنسانية طارئة وبرامج الرعاية الصحية والتعليم المستمرة.',
    office: 'Brazzaville Humanitarian Hub',
    officeAr: 'مركز برازافيل الإنساني',
  },
  {
    id: 21,
    slug: 'egypt',
    name: 'Egypt',
    nameAr: 'مصر',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇪🇬',
    programs: ['Healthcare', 'Education', 'Livelihood Training', 'Food Security'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش', 'الأمن الغذائي'],
    impact: '18,500+ beneficiaries',
    impactAr: '18,500+ مستفيد',
    description: 'Comprehensive medical clinics, educational scholarships, vocational training, and food assistance programs.',
    descriptionAr: 'عيادات طبية شاملة، منح دراسية، تدريب مهني، وبرامج المساعدة الغذائية.',
    office: 'Cairo Central Headquarters',
    officeAr: 'مقر القاهرة المركزي',
  },
  {
    id: 22,
    slug: 'ivory-coast',
    name: 'Ivory Coast',
    nameAr: 'ساحل العاج',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇨🇮',
    programs: ['Education', 'Healthcare', 'Livelihood Support'],
    programsAr: ['التعليم', 'الرعاية الصحية', 'دعم سبل العيش'],
    impact: '6,200+ students & workers trained',
    impactAr: '6,200+ طالب وعامل مُدرّب',
    description: 'Educational programs, medical clinics, and livelihood training for vulnerable populations.',
    descriptionAr: 'برامج تعليمية وعيادات طبية وتدريب سبل العيش للفئات الضعيفة.',
    office: 'Abidjan Regional Office',
    officeAr: 'مكتب أبيدجان الإقليمي',
  },
  {
    id: 23,
    slug: 'liberia',
    name: 'Liberia',
    nameAr: 'ليبيريا',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇱🇷',
    programs: ['Healthcare', 'Education', 'Livelihood Training'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش'],
    impact: '7,800+ beneficiaries',
    impactAr: '7,800+ مستفيد',
    description: 'Medical clinics, educational support, and vocational training programs.',
    descriptionAr: 'عيادات طبية ودعم تعليمي وبرامج تدريب مهني.',
    office: 'Monrovia Operations Center',
    officeAr: 'مركز مونروفيا التشغيلي',
  },
  {
    id: 24,
    slug: 'libya',
    name: 'Libya',
    nameAr: 'ليبيا',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇱🇾',
    programs: ['Crisis Response', 'Healthcare', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي'],
    impact: '16,500+ crisis-affected supported',
    impactAr: '16,500+ متضرر من الأزمات مدعوم',
    description: 'Emergency humanitarian assistance, medical support, and food distribution.',
    descriptionAr: 'مساعدة إنسانية طارئة ودعم طبي وتوزيع غذاء.',
    office: 'Tripoli Crisis Response Center',
    officeAr: 'مركز طرابلس للاستجابة للأزمات',
  },
  {
    id: 25,
    slug: 'morocco',
    name: 'Morocco',
    nameAr: 'المغرب',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇲🇦',
    programs: ['Healthcare', 'Education', 'Livelihood Training'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش'],
    impact: '9,100+ beneficiaries',
    impactAr: '9,100+ مستفيد',
    description: 'Healthcare clinics, educational scholarships, and vocational training initiatives.',
    descriptionAr: 'عيادات الرعاية الصحية والمنح الدراسية ومبادرات التدريب المهني.',
    office: 'Casablanca Regional Hub',
    officeAr: 'مركز الدار البيضاء الإقليمي',
  },
  {
    id: 26,
    slug: 'somalia',
    name: 'Somalia',
    nameAr: 'الصومال',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇸🇴',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم'],
    impact: '24,000+ crisis-affected supported',
    impactAr: '24,000+ متضرر من الأزمات مدعوم',
    description: 'Large-scale humanitarian programs addressing food insecurity, healthcare needs, and educational support.',
    descriptionAr: 'برامج إنسانية واسعة النطاق تعالج انعدام الأمن الغذائي واحتياجات الرعاية الصحية والدعم التعليمي.',
    office: 'Mogadishu Humanitarian Hub',
    officeAr: 'مركز مقديشو الإنساني',
  },
  {
    id: 27,
    slug: 'sudan',
    name: 'Sudan',
    nameAr: 'السودان',
    region: 'africa',
    regionAr: 'أفريقيا',
    flag: '🇸🇩',
    programs: ['Crisis Response', 'Healthcare', 'Food Security', 'Education'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي', 'التعليم'],
    impact: '42,000+ crisis-affected supported',
    impactAr: '42,000+ متضرر من الأزمات مدعوم',
    description: 'Major humanitarian operations including emergency relief, medical services, food assistance, and educational support.',
    descriptionAr: 'عمليات إنسانية كبرى تشمل الإغاثة الطارئة والخدمات الطبية والمساعدة الغذائية والدعم التعليمي.',
    office: 'Khartoum Emergency Operations',
    officeAr: 'عمليات الخرطوم الطارئة',
  },

  // EUROPE
  {
    id: 28,
    slug: 'abkhazia',
    name: 'Abkhazia',
    nameAr: 'أبخازيا',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇬🇪',
    programs: ['Crisis Response', 'Healthcare', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي'],
    impact: '5,500+ conflict-affected supported',
    impactAr: '5,500+ متضرر من الصراع مدعوم',
    description: 'Emergency humanitarian assistance to conflict-affected population.',
    descriptionAr: 'مساعدة إنسانية طارئة للسكان المتأثرين بالصراع.',
    office: 'Sukhumi Operations Center',
    officeAr: 'مركز سوخومي التشغيلي',
  },
  {
    id: 29,
    slug: 'bosnia',
    name: 'Bosnia',
    nameAr: 'البوسنة',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇧🇦',
    programs: ['Healthcare', 'Education', 'Livelihood Support'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'دعم سبل العيش'],
    impact: '6,800+ beneficiaries',
    impactAr: '6,800+ مستفيد',
    description: 'Post-conflict recovery programs including healthcare, education, and economic support.',
    descriptionAr: 'برامج التعافي بعد الصراع تشمل الرعاية الصحية والتعليم والدعم الاقتصادي.',
    office: 'Sarajevo Regional Office',
    officeAr: 'مكتب سراييفو الإقليمي',
  },
  {
    id: 30,
    slug: 'bulgaria',
    name: 'Bulgaria',
    nameAr: 'بلغاريا',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇧🇬',
    programs: ['Healthcare', 'Education'],
    programsAr: ['الرعاية الصحية', 'التعليم'],
    impact: '4,200+ beneficiaries',
    impactAr: '4,200+ مستفيد',
    description: 'Medical clinics and educational programs for vulnerable communities.',
    descriptionAr: 'عيادات طبية وبرامج تعليمية للمجتمعات الضعيفة.',
    office: 'Sofia Operations Office',
    officeAr: 'مكتب صوفيا التشغيلي',
  },
  {
    id: 31,
    slug: 'chechnya',
    name: 'Chechnya',
    nameAr: 'الشيشان',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇷🇺',
    programs: ['Crisis Response', 'Healthcare', 'Livelihood Support'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'دعم سبل العيش'],
    impact: '7,600+ conflict-affected supported',
    impactAr: '7,600+ متضرر من الصراع مدعوم',
    description: 'Humanitarian assistance for conflict-affected population including medical and economic support.',
    descriptionAr: 'المساعدة الإنسانية للسكان المتأثرين بالصراع تشمل الدعم الطبي والاقتصادي.',
    office: 'Grozny Emergency Hub',
    officeAr: 'مركز غروزني الطارئ',
  },
  {
    id: 32,
    slug: 'macedonia',
    name: 'Macedonia',
    nameAr: 'مقدونيا',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇲🇰',
    programs: ['Healthcare', 'Education', 'Livelihood Support'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'دعم سبل العيش'],
    impact: '5,300+ beneficiaries',
    impactAr: '5,300+ مستفيد',
    description: 'Healthcare delivery, educational scholarships, and livelihood programs.',
    descriptionAr: 'توصيل الرعاية الصحية والمنح الدراسية وبرامج سبل العيش.',
    office: 'Skopje Regional Center',
    officeAr: 'مركز سكوبيا الإقليمي',
  },
  {
    id: 33,
    slug: 'romania',
    name: 'Romania',
    nameAr: 'رومانيا',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇷🇴',
    programs: ['Healthcare', 'Education'],
    programsAr: ['الرعاية الصحية', 'التعليم'],
    impact: '4,900+ beneficiaries',
    impactAr: '4,900+ مستفيد',
    description: 'Medical clinics and educational support for vulnerable populations.',
    descriptionAr: 'عيادات طبية ودعم تعليمي للفئات الضعيفة.',
    office: 'Bucharest Operations Office',
    officeAr: 'مكتب بوخارست التشغيلي',
  },
  {
    id: 34,
    slug: 'south-ossetia',
    name: 'South Ossetia',
    nameAr: 'أوسيتيا الجنوبية',
    region: 'europe',
    regionAr: 'أوروبا',
    flag: '🇬🇪',
    programs: ['Crisis Response', 'Healthcare', 'Food Security'],
    programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'الأمن الغذائي'],
    impact: '4,800+ conflict-affected supported',
    impactAr: '4,800+ متضرر من الصراع مدعوم',
    description: 'Emergency humanitarian assistance to conflict-affected communities.',
    descriptionAr: 'مساعدة إنسانية طارئة للمجتمعات المتأثرة بالصراع.',
    office: 'Tskhinvali Operations',
    officeAr: 'عمليات تسخينفالي',
  },

  // MIDDLE-EAST
  {
    id: 36,
    slug: 'jordan',
    name: 'Jordan',
    nameAr: 'الأردن',
    region: 'middle-east',
    regionAr: 'الشرق الأوسط',
    flag: '🇯🇴',
    programs: ['Healthcare', 'Education', 'Livelihoods', 'Refugee Support'],
    programsAr: ['الرعاية الصحية', 'التعليم', 'سبل العيش', 'دعم اللاجئين'],
    impact: '38,000+ refugee families supported',
    impactAr: '38,000+ أسرة لاجئة مدعومة',
    description: 'JHCO operates a major regional hub in Jordan supporting refugees and vulnerable populations with healthcare, education, vocational training, and livelihood programs.',
    descriptionAr: 'تشغل الهيئة مركزاً إقليمياً رئيسياً في الأردن يدعم اللاجئين والفئات الضعيفة بالرعاية الصحية والتعليم والتدريب المهني وبرامج سبل العيش.',
    office: 'Amman Regional Headquarters',
    officeAr: 'مقر عمّان الإقليمي',
  },

  // AMERICAS
  {
    id: 35,
    slug: 'haiti',
    name: 'Haiti',
    nameAr: 'هايتي',
    region: 'americas',
    regionAr: 'الأمريكتان',
    flag: '🇭🇹',
    programs: ['Disaster Relief', 'Healthcare', 'Education', 'Livelihood Training'],
    programsAr: ['إغاثة الكوارث', 'الرعاية الصحية', 'التعليم', 'تدريب سبل العيش'],
    impact: '28,000+ hurricane survivors supported',
    impactAr: '28,000+ ناجي من الأعاصير مدعوم',
    description: 'Comprehensive disaster relief operations, healthcare clinics, educational scholarships, and vocational training programs.',
    descriptionAr: 'عمليات إغاثة كوارث شاملة وعيادات طبية ومنح دراسية وبرامج تدريب مهني.',
    office: 'Port-au-Prince Coordination Hub',
    officeAr: 'مركز بورت أو برنس التنسيقي',
  },
];

export const mobileApps = [
  {
    id: 1,
    slug: 'jhco-connect',
    name: 'JHCO Connect',
    nameAr: 'الهيئة تتصل',
    description: 'Donate, volunteer, and stay updated on JHCO initiatives with our main mobile app',
    descriptionAr: 'تبرع وتطوع وابق محدثاً بشأن مبادرات الهيئة من خلال تطبيق الهاتف المحمول الخاص بنا',
    longDescription: 'The official JHCO Connect app provides seamless access to donation features, volunteer opportunities, real-time impact tracking, and exclusive updates from the field. Stay connected with our humanitarian mission wherever you are.',
    longDescriptionAr: 'يوفر تطبيق JHCO Connect الرسمي الوصول السلس إلى ميزات التبرع وفرص التطوع وتتبع التأثير في الوقت الفعلي والتحديثات الحصرية من الميدان. ابق متصلاً بمهمتنا الإنسانية أينما كنت.',
    features: ['Quick Donation', 'Volunteer Signup', 'Impact Tracking', 'Push Notifications', 'Offline Access', 'Multi-language Support'],
    featuresAr: ['التبرع السريع', 'التسجيل للتطوع', 'تتبع التأثير', 'إشعارات فورية', 'الوصول بدون اتصال', 'دعم اللغات المتعددة'],
    rating: 4.8,
    reviews: 2547,
    downloads: '100K+',
    category: 'Main App',
    categoryAr: 'التطبيق الرئيسي',
    icon: '📱',
  },
  {
    id: 2,
    slug: 'jhco-donor',
    name: 'JHCO Donor',
    nameAr: 'المتبرع الخيري',
    description: 'Advanced donor portal for tracking contributions and receiving detailed impact reports',
    descriptionAr: 'بوابة متقدمة للمانحين لتتبع المساهمات وتلقي تقارير تأثير مفصلة',
    longDescription: 'Exclusively designed for our valued donors, JHCO Donor provides comprehensive dashboards, tax documentation, impact reports, and direct communication channels with our programs. Watch your contribution make a difference.',
    longDescriptionAr: 'مصمم خصيصاً لمانحينا الموقرين، يوفر تطبيق المتبرع الخيري لوحات معلومات شاملة وتوثيق ضريبي وتقارير التأثير وقنوات اتصال مباشرة مع برامجنا. شاهد مساهمتك تحدث فرقاً.',
    features: ['Donation History', 'Tax Documents', 'Impact Reports', 'Program Updates', 'Direct Messaging', 'Receipt Management'],
    featuresAr: ['سجل التبرعات', 'المستندات الضريبية', 'تقارير التأثير', 'تحديثات البرنامج', 'الرسائل المباشرة', 'إدارة الإيصالات'],
    rating: 4.9,
    reviews: 1834,
    downloads: '50K+',
    category: 'Donor Tools',
    categoryAr: 'أدوات المانحين',
    icon: '💳',
  },
  {
    id: 3,
    slug: 'jhco-volunteer',
    name: 'JHCO Volunteer',
    nameAr: 'متطوع الهيئة',
    description: 'Comprehensive volunteer management app with scheduling, training, and coordination features',
    descriptionAr: 'تطبيق شامل لإدارة المتطوعين مع ميزات الجدولة والتدريب والتنسيق',
    longDescription: 'The ultimate companion for JHCO volunteers, featuring shift scheduling, task assignments, training materials, team communication, and real-time coordination of humanitarian efforts across the globe.',
    longDescriptionAr: 'الرفيق النهائي لمتطوعي الهيئة، يتضمن جدولة الفترات وتعيين المهام والمواد التدريبية واتصالات الفريق والتنسيق الفعلي للجهود الإنسانية حول العالم.',
    features: ['Shift Scheduling', 'Task Management', 'Training Portal', 'Team Chat', 'Impact Tracking', 'Certification'],
    featuresAr: ['جدولة الفترات', 'إدارة المهام', 'بوابة التدريب', 'دردشة الفريق', 'تتبع التأثير', 'الشهادات'],
    rating: 4.7,
    reviews: 3125,
    downloads: '75K+',
    category: 'Volunteer Tools',
    categoryAr: 'أدوات المتطوعين',
    icon: '🤝',
  },
  {
    id: 4,
    slug: 'jhco-beneficiary',
    name: 'JHCO Beneficiary',
    nameAr: 'المستفيد من الهيئة',
    description: 'Support app for program beneficiaries to access services and track assistance',
    descriptionAr: 'تطبيق الدعم للمستفيدين من البرامج للوصول إلى الخدمات وتتبع المساعدة',
    longDescription: 'Empowering beneficiaries of our programs with direct access to services, appointment scheduling, resource directory, education materials, and real-time support from JHCO staff.',
    longDescriptionAr: 'تمكين المستفيدين من برامجنا بالوصول المباشر إلى الخدمات وجدولة المواعيد ودليل الموارد والمواد التعليمية والدعم الفعلي من موظفي الهيئة.',
    features: ['Service Access', 'Appointment Booking', 'Resource Library', 'Educational Content', 'Support Chat', 'Progress Tracking'],
    featuresAr: ['الوصول إلى الخدمات', 'حجز المواعيد', 'مكتبة الموارد', 'المحتوى التعليمي', 'دردشة الدعم', 'تتبع التقدم'],
    rating: 4.6,
    reviews: 2156,
    downloads: '60K+',
    category: 'Beneficiary Portal',
    categoryAr: 'بوابة المستفيدين',
    icon: '🎯',
  },
  {
    id: 5,
    slug: 'jhco-field-ops',
    name: 'JHCO Field Ops',
    nameAr: 'عمليات الهيئة الميدانية',
    description: 'Real-time field operations management for coordinating humanitarian efforts',
    descriptionAr: 'إدارة العمليات الميدانية الفعلية لتنسيق الجهود الإنسانية',
    longDescription: 'Built for field coordinators and operational teams, JHCO Field Ops enables real-time GPS tracking, supply inventory management, incident reporting, and team coordination across multiple regions.',
    longDescriptionAr: 'مُنشأ لمنسقي الميدان والفرق التشغيلية، يوفر تطبيق العمليات الميدانية تتبعاً فعلياً بنظام GPS وإدارة مخزون الإمدادات والإبلاغ عن الحوادث والتنسيق بين الفرق عبر عدة مناطق.',
    features: ['GPS Tracking', 'Inventory Management', 'Incident Reporting', 'Team Coordination', 'Geofencing', 'Offline Maps'],
    featuresAr: ['تتبع GPS', 'إدارة المخزون', 'الإبلاغ عن الحوادث', 'تنسيق الفريق', 'الحدود الجغرافية', 'الخرائط بدون اتصال'],
    rating: 4.5,
    reviews: 892,
    downloads: '25K+',
    category: 'Operations',
    categoryAr: 'العمليات',
    icon: '🗺️',
  },
  {
    id: 6,
    slug: 'jhco-education',
    name: 'JHCO Education Hub',
    nameAr: 'مركز التعليم الخيري',
    description: 'Learning platform for educational programs and scholarship management',
    descriptionAr: 'منصة التعلم لبرامج التعليم وإدارة المنح الدراسية',
    longDescription: 'Comprehensive education platform featuring online courses, scholarship applications, progress tracking, mentorship connections, and career development resources for students enrolled in JHCO programs.',
    longDescriptionAr: 'منصة تعليمية شاملة تتضمن دورات عبر الإنترنت وطلبات المنح الدراسية وتتبع التقدم وتوصيلات الإرشاد وموارد التطوير الوظيفي للطلاب المسجلين في برامج الهيئة.',
    features: ['Online Courses', 'Scholarship Portal', 'Progress Tracking', 'Mentorship', 'Career Resources', 'Peer Community'],
    featuresAr: ['الدورات عبر الإنترنت', 'بوابة المنح', 'تتبع التقدم', 'الإرشاد', 'موارد الوظائف', 'مجتمع الأقران'],
    rating: 4.7,
    reviews: 1432,
    downloads: '40K+',
    category: 'Education',
    categoryAr: 'التعليم',
    icon: '📚',
  },
];

export const volunteerOpportunities = [
  {
    id: 1,
    slug: 'field-coordinator-gaza',
    title: 'Field Coordinator - Gaza',
    titleAr: 'منسق ميداني - غزة',
    category: 'Field',
    categoryAr: 'ميداني',
    type: 'On-Site',
    typeAr: 'في الموقع',
    location: 'Gaza Strip',
    locationAr: 'قطاع غزة',
    commitment: '3-6 months',
    commitmentAr: '3-6 أشهر',
    description: 'Coordinate humanitarian relief operations in Gaza, managing logistics, distribution, and community engagement.',
    descriptionAr: 'تنسيق عمليات الإغاثة الإنسانية في غزة، إدارة الخدمات اللوجستية والتوزيع والتفاعل المجتمعي.',
    requirements: ['2+ years project management experience', 'Arabic language skills', 'Crisis management experience', 'Flexibility and adaptability'],
    requirementsAr: ['خبرة 2+ سنة في إدارة المشاريع', 'مهارات اللغة العربية', 'خبرة في إدارة الأزمات', 'المرونة والقدرة على التكيف'],
    skills: ['Project Management', 'Leadership', 'Communication', 'Crisis Management'],
    skillsAr: ['إدارة المشاريع', 'القيادة', 'التواصل', 'إدارة الأزمات'],
    impact: 'Direct impact on 5,000+ families',
    impactAr: 'تأثير مباشر على 5,000+ أسرة',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🌍',
  },
  {
    id: 2,
    slug: 'healthcare-volunteer',
    title: 'Healthcare Volunteer - Medical Clinics',
    titleAr: 'متطوع الرعاية الصحية - العيادات الطبية',
    category: 'Field',
    categoryAr: 'ميداني',
    type: 'On-Site',
    typeAr: 'في الموقع',
    location: 'Multiple Regions',
    locationAr: 'مناطق متعددة',
    commitment: '2-4 months',
    commitmentAr: '2-4 أشهر',
    description: 'Support healthcare delivery in our medical clinics across regions. Assist doctors and nurses in patient care.',
    descriptionAr: 'دعم تقديم الرعاية الصحية في عياداتنا الطبية عبر المناطق. مساعدة الأطباء والممرضات في رعاية المرضى.',
    requirements: ['Medical background preferred', 'Basic healthcare knowledge', 'Compassion for vulnerable populations', 'Physical stamina'],
    requirementsAr: ['خلفية طبية مفضلة', 'معرفة أساسية بالرعاية الصحية', 'التعاطف مع الفئات الضعيفة', 'القدرة على البقاء واقفاً'],
    skills: ['Healthcare', 'Patient Care', 'Empathy', 'Physical Health'],
    skillsAr: ['الرعاية الصحية', 'رعاية المرضى', 'التعاطف', 'الصحة البدنية'],
    impact: 'Support 3,000+ patient visits',
    impactAr: 'دعم 3,000+ زيارة مريض',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🏥',
  },
  {
    id: 3,
    slug: 'education-tutor-remote',
    title: 'Education Tutor - Remote',
    titleAr: 'معلم دروس خصوصية - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '10-15 hours/week',
    commitmentAr: '10-15 ساعة/أسبوع',
    description: 'Provide online tutoring to students in underserved communities. Help them excel in core subjects.',
    descriptionAr: 'تقديم دروس خصوصية عبر الإنترنت للطلاب في المجتمعات الفقيرة. ساعدهم في التفوق في المواد الأساسية.',
    requirements: ['Teaching experience', 'Subject matter expertise', 'Online communication skills', 'Patience and dedication'],
    requirementsAr: ['خبرة تعليمية', 'خبرة متخصصة', 'مهارات التواصل عبر الإنترنت', 'الصبر والتفاني'],
    skills: ['Teaching', 'Communication', 'Patience', 'Subject Knowledge'],
    skillsAr: ['التدريس', 'التواصل', 'الصبر', 'المعرفة المتخصصة'],
    impact: 'Help 200+ students improve grades',
    impactAr: 'ساعد 200+ طالب على تحسين الدرجات',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🎓',
  },
  {
    id: 4,
    slug: 'data-analyst-remote',
    title: 'Data Analyst - Remote',
    titleAr: 'محلل بيانات - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '15-20 hours/week',
    commitmentAr: '15-20 ساعة/أسبوع',
    description: 'Analyze program impact data and create insights to improve humanitarian initiatives effectiveness.',
    descriptionAr: 'تحليل بيانات تأثير البرنامج وإنشاء رؤى لتحسين فعالية المبادرات الإنسانية.',
    requirements: ['Data analysis expertise', 'Excel/SQL proficiency', 'Attention to detail', 'Reporting skills'],
    requirementsAr: ['خبرة تحليل البيانات', 'إتقان Excel/SQL', 'الاهتمام بالتفاصيل', 'مهارات الإبلاغ'],
    skills: ['Data Analysis', 'Excel', 'SQL', 'Communication'],
    skillsAr: ['تحليل البيانات', 'Excel', 'SQL', 'التواصل'],
    impact: 'Improve program efficiency for 15+ initiatives',
    impactAr: 'تحسين كفاءة البرنامج لـ 15+ مبادرة',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '📊',
  },
  {
    id: 5,
    slug: 'content-writer-remote',
    title: 'Content Writer - Remote',
    titleAr: 'كاتب محتوى - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '8-12 hours/week',
    commitmentAr: '8-12 ساعة/أسبوع',
    description: 'Create compelling stories about our humanitarian work and volunteer experiences. Help amplify our impact.',
    descriptionAr: 'إنشاء قصص جذابة عن عملنا الإنساني وتجارب المتطوعين. ساعد في تضخيم تأثيرنا.',
    requirements: ['Excellent writing skills', 'Storytelling ability', 'Bilingual (English/Arabic) preferred', 'Social media knowledge'],
    requirementsAr: ['مهارات الكتابة الممتازة', 'القدرة على سرد القصص', 'ثنائي اللغة (إنجليزي/عربي) مفضل', 'معرفة وسائل التواصل الاجتماعي'],
    skills: ['Writing', 'Storytelling', 'Communication', 'Social Media'],
    skillsAr: ['الكتابة', 'سرد القصص', 'التواصل', 'وسائل التواصل الاجتماعي'],
    impact: 'Reach 50,000+ people monthly with stories',
    impactAr: 'الوصول إلى 50,000+ شخص شهرياً بالقصص',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '✍️',
  },
  {
    id: 6,
    slug: 'graphic-designer-remote',
    title: 'Graphic Designer - Remote',
    titleAr: 'مصمم جرافيك - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '12-16 hours/week',
    commitmentAr: '12-16 ساعة/أسبوع',
    description: 'Design visual materials for campaigns and communications. Create engaging graphics for social media and reports.',
    descriptionAr: 'تصميم المواد البصرية للحملات والاتصالات. إنشاء رسومات جذابة لوسائل التواصل الاجتماعي والتقارير.',
    requirements: ['Graphic design expertise', 'Proficiency in design software', 'Creative thinking', 'Brand understanding'],
    requirementsAr: ['خبرة تصميم جرافيك', 'إتقان برامج التصميم', 'التفكير الإبداعي', 'فهم العلامة التجارية'],
    skills: ['Graphic Design', 'Adobe Suite', 'Creativity', 'Brand Design'],
    skillsAr: ['تصميم جرافيك', 'Adobe Suite', 'الإبداع', 'تصميم العلامة التجارية'],
    impact: 'Create 50+ design assets monthly',
    impactAr: 'إنشاء 50+ أصل تصميمي شهرياً',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🎨',
  },
  {
    id: 7,
    slug: 'translator-remote',
    title: 'Translator - Remote (Arabic/English)',
    titleAr: 'مترجم - عن بُعد (عربي/إنجليزي)',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '10-20 hours/week',
    commitmentAr: '10-20 ساعة/أسبوع',
    description: 'Translate documents, reports, and communications between Arabic and English. Bridge language barriers in our work.',
    descriptionAr: 'ترجمة المستندات والتقارير والاتصالات بين العربية والإنجليزية. تجسير الفجوات اللغوية في عملنا.',
    requirements: ['Native/fluent in Arabic and English', 'Translation experience', 'Cultural sensitivity', 'Attention to detail'],
    requirementsAr: ['أصلي/بطلاقة في العربية والإنجليزية', 'خبرة الترجمة', 'الحساسية الثقافية', 'الاهتمام بالتفاصيل'],
    skills: ['Translation', 'Arabic', 'English', 'Communication'],
    skillsAr: ['الترجمة', 'العربية', 'الإنجليزية', 'التواصل'],
    impact: 'Translate 100+ documents monthly',
    impactAr: 'ترجمة 100+ مستند شهرياً',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '🌐',
  },
  {
    id: 8,
    slug: 'administrative-support',
    title: 'Administrative Support - Remote',
    titleAr: 'الدعم الإداري - عن بُعد',
    category: 'Administrative',
    categoryAr: 'إداري',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '12-15 hours/week',
    commitmentAr: '12-15 ساعة/أسبوع',
    description: 'Provide administrative support including scheduling, email management, and document organization.',
    descriptionAr: 'تقديم الدعم الإداري بما فيه جدولة المواعيد وإدارة البريد الإلكتروني وتنظيم المستندات.',
    requirements: ['Organizational skills', 'Office software proficiency', 'Attention to detail', 'Communication skills'],
    requirementsAr: ['مهارات تنظيمية', 'إتقان برامج المكتب', 'الاهتمام بالتفاصيل', 'مهارات التواصل'],
    skills: ['Organization', 'Office Management', 'Communication', 'Problem Solving'],
    skillsAr: ['التنظيم', 'إدارة المكتب', 'التواصل', 'حل المشاكل'],
    impact: 'Support 5+ teams efficiently',
    impactAr: 'دعم 5+ فرق بكفاءة',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '📋',
  },
  {
    id: 9,
    slug: 'social-media-manager',
    title: 'Social Media Manager - Remote',
    titleAr: 'مدير وسائل التواصل - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '15-20 hours/week',
    commitmentAr: '15-20 ساعة/أسبوع',
    description: 'Manage our social media accounts, create engaging content, and grow our online community.',
    descriptionAr: 'إدارة حساباتنا على وسائل التواصل والمحتوى الجذاب وتنمية مجتمعنا عبر الإنترنت.',
    requirements: ['Social media expertise', 'Content creation skills', 'Analytics knowledge', 'Community management experience'],
    requirementsAr: ['خبرة وسائل التواصل', 'مهارات إنشاء المحتوى', 'معرفة التحليلات', 'خبرة إدارة المجتمع'],
    skills: ['Social Media', 'Content Creation', 'Analytics', 'Community Management'],
    skillsAr: ['وسائل التواصل', 'إنشاء المحتوى', 'التحليلات', 'إدارة المجتمع'],
    impact: 'Reach 100,000+ followers',
    impactAr: 'الوصول إلى 100,000+ متابع',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '📱',
  },
  {
    id: 10,
    slug: 'youth-mentor-field',
    title: 'Youth Mentor - Field Program',
    titleAr: 'مرشد شباب - برنامج ميداني',
    category: 'Field',
    categoryAr: 'ميداني',
    type: 'On-Site',
    typeAr: 'في الموقع',
    location: 'Multiple Regions',
    locationAr: 'مناطق متعددة',
    commitment: '3-4 months',
    commitmentAr: '3-4 أشهر',
    description: 'Mentor young people in skill development and career guidance. Help them achieve their potential.',
    descriptionAr: 'إرشاد الشباب في تطوير المهارات والتوجيه المهني. ساعدهم على تحقيق إمكاناتهم.',
    requirements: ['Mentoring experience', 'Leadership skills', 'Passion for youth development', 'Patience and empathy'],
    requirementsAr: ['خبرة الإرشاد', 'مهارات القيادة', 'الشغف بتطوير الشباب', 'الصبر والتعاطف'],
    skills: ['Mentoring', 'Leadership', 'Communication', 'Youth Development'],
    skillsAr: ['الإرشاد', 'القيادة', 'التواصل', 'تطوير الشباب'],
    impact: 'Guide 150+ young people',
    impactAr: 'إرشاد 150+ شاب',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '👥',
  },
  {
    id: 11,
    slug: 'logistics-coordinator',
    title: 'Logistics Coordinator - Field',
    titleAr: 'منسق الخدمات اللوجستية - ميداني',
    category: 'Field',
    categoryAr: 'ميداني',
    type: 'On-Site',
    typeAr: 'في الموقع',
    location: 'Multiple Regions',
    locationAr: 'مناطق متعددة',
    commitment: '4-6 months',
    commitmentAr: '4-6 أشهر',
    description: 'Coordinate supplies, equipment, and distribution logistics for humanitarian operations.',
    descriptionAr: 'تنسيق المستلزمات والمعدات والخدمات اللوجستية للتوزيع للعمليات الإنسانية.',
    requirements: ['Logistics experience', 'Problem-solving skills', 'Attention to detail', 'Physical capability'],
    requirementsAr: ['خبرة لوجستية', 'مهارات حل المشاكل', 'الاهتمام بالتفاصيل', 'القدرة البدنية'],
    skills: ['Logistics', 'Organization', 'Problem Solving', 'Leadership'],
    skillsAr: ['الخدمات اللوجستية', 'التنظيم', 'حل المشاكل', 'القيادة'],
    impact: 'Deliver 10,000+ aid packages',
    impactAr: 'توصيل 10,000+ حزمة إغاثة',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '📦',
  },
  {
    id: 12,
    slug: 'web-developer-remote',
    title: 'Web Developer - Remote',
    titleAr: 'مطور ويب - عن بُعد',
    category: 'Remote',
    categoryAr: 'بعيد',
    type: 'Remote',
    typeAr: 'عن بُعد',
    location: 'Work from Home',
    locationAr: 'العمل من المنزل',
    commitment: '15-20 hours/week',
    commitmentAr: '15-20 ساعة/أسبوع',
    description: 'Develop and maintain web applications that help manage our programs and reach beneficiaries.',
    descriptionAr: 'تطوير والحفاظ على تطبيقات ويب تساعد في إدارة برامجنا والوصول إلى المستفيدين.',
    requirements: ['Web development experience', 'JavaScript proficiency', 'Problem-solving skills', 'Git knowledge'],
    requirementsAr: ['خبرة تطوير الويب', 'إتقان JavaScript', 'مهارات حل المشاكل', 'معرفة Git'],
    skills: ['Web Development', 'JavaScript', 'React/Vue', 'Database Design'],
    skillsAr: ['تطوير الويب', 'JavaScript', 'React/Vue', 'تصميم قواعد البيانات'],
    impact: 'Improve digital reach for 100,000+ users',
    impactAr: 'تحسين الوصول الرقمي لـ 100,000+ مستخدم',
    status: 'Open',
    statusAr: 'مفتوح',
    icon: '💻',
  },
];

export const regionalData = {
  africa: {
    overview: {
      headline: 'Africa Regional Hub',
      headlineAr: 'مركز أفريقيا الإقليمي',
      description: 'JHCO operates transformational humanitarian programs across 10 African nations, providing crisis response, healthcare, education, and livelihood support to vulnerable communities. Our Africa operations represent one of the most critical humanitarian engagements, reaching hundreds of thousands of families with dignified support.',
      descriptionAr: 'تعمل الهيئة على برامج إنسانية تحويلية عبر 10 دول أفريقية، توفر الاستجابة للأزمات والرعاية الصحية والتعليم ودعم سبل العيش للمجتمعات الضعيفة. تمثل عمليات أفريقيا لدينا أحد أهم الالتزامات الإنسانية، حيث تصل إلى مئات الآلاف من الأسر بدعم كريم.',
    },
    statistics: [
      { value: '10', label: 'Countries Served', labelAr: 'الدول المخدومة', icon: '🌍' },
      { value: '98,500+', label: 'Direct Beneficiaries', labelAr: 'المستفيدون المباشرون', icon: '❤️' },
      { value: '25+', label: 'Active Programs', labelAr: 'البرامج النشطة', icon: '📊' },
      { value: '450+', label: 'Field Staff', labelAr: 'الموظفون الميدانيون', icon: '👥' },
    ],
    countryBreakdown: [
      {
        slug: 'egypt',
        name: 'Egypt',
        nameAr: 'مصر',
        flag: '🇪🇬',
        beneficiaries: '18,500+',
        programs: ['Healthcare', 'Education', 'Livelihood Training', 'Food Security'],
        programsAr: ['الرعاية الصحية', 'التعليم', 'تدريب سبل العيش', 'الأمن الغذائي'],
        office: 'Cairo Central Headquarters',
        officeAr: 'مقر القاهرة المركزي',
        highlights: ['12 medical clinics', '850 students supported', '2,200+ livelihoods trained'],
        highlightsAr: ['12 عيادة طبية', '850 طالب مدعوم', '2,200+ سبل عيش مدربة'],
      },
      {
        slug: 'sudan',
        name: 'Sudan',
        nameAr: 'السودان',
        flag: '🇸🇩',
        beneficiaries: '22,000+',
        programs: ['Crisis Response', 'Food Security', 'Healthcare', 'Water & Sanitation'],
        programsAr: ['الاستجابة للأزمات', 'الأمن الغذائي', 'الرعاية الصحية', 'المياه والصرف'],
        office: 'Khartoum Emergency Hub',
        officeAr: 'مركز الخرطوم الطارئ',
        highlights: ['Emergency aid to 10,000 families', '15 water points installed', '4,000 food packages/month'],
        highlightsAr: ['مساعدة طارئة لـ 10,000 أسرة', '15 نقطة مياه مثبتة', '4,000 حزمة غذاء/شهر'],
      },
      {
        slug: 'somalia',
        name: 'Somalia',
        nameAr: 'الصومال',
        flag: '🇸🇴',
        beneficiaries: '16,800+',
        programs: ['Food Security', 'Healthcare', 'Water & Sanitation', 'Education'],
        programsAr: ['الأمن الغذائي', 'الرعاية الصحية', 'المياه والصرف', 'التعليم'],
        office: 'Mogadishu Operations Center',
        officeAr: 'مركز مقديشو التشغيلي',
        highlights: ['200,000+ people reached monthly', '8 mobile clinics', '3,500 school meals/day'],
        highlightsAr: ['200,000+ شخص تم الوصول إليهم شهرياً', '8 عيادات متنقلة', '3,500 وجبة مدرسية/يوم'],
      },
      {
        slug: 'algeria',
        name: 'Algeria',
        nameAr: 'الجزائر',
        flag: '🇩🇿',
        beneficiaries: '8,500+',
        programs: ['Healthcare', 'Education', 'Food Security', 'Livelihoods'],
        programsAr: ['الرعاية الصحية', 'التعليم', 'الأمن الغذائي', 'سبل العيش'],
        office: 'Algiers Regional Office',
        officeAr: 'مكتب الجزائر الإقليمي',
        highlights: ['6 medical clinics', '1,200+ students', '800+ trained in vocational skills'],
        highlightsAr: ['6 عيادات طبية', '1,200+ طالب', '800+ مدربين في المهارات المهنية'],
      },
      {
        slug: 'congo',
        name: 'Congo',
        nameAr: 'الكونغو',
        flag: '🇨🇬',
        beneficiaries: '12,000+',
        programs: ['Crisis Response', 'Healthcare', 'Education', 'Community Programs'],
        programsAr: ['الاستجابة للأزمات', 'الرعاية الصحية', 'التعليم', 'برامج المجتمع'],
        office: 'Brazzaville Humanitarian Hub',
        officeAr: 'مركز برازافيل الإنساني',
        highlights: ['Emergency response to 8,000 families', '4 healthcare centers', '2,500 students supported'],
        highlightsAr: ['الاستجابة الطارئة لـ 8,000 أسرة', '4 مراكز رعاية صحية', '2,500 طالب مدعوم'],
      },
    ],
    regionalChallenges: [
      {
        title: 'Humanitarian Access & Insecurity',
        titleAr: 'الوصول الإنساني وعدم الاستقرار',
        description: 'Ongoing conflict and insecurity in several countries limit humanitarian access and endanger field teams.',
        descriptionAr: 'الصراعات المستمرة وعدم الاستقرار في عدة دول تحد من الوصول الإنساني وتعرض فرق الميدان للخطر.',
        solution: 'JHCO works through local partners and community networks, employing conflict-sensitive approaches and maintaining strong security protocols to ensure safe program delivery.',
        solutionAr: 'تعمل الهيئة من خلال الشركاء المحليين وشبكات المجتمع، وتستخدم أساليب حساسة للصراع وتحافظ على بروتوكولات أمنية قوية لضمان توصيل البرنامج الآمن.',
      },
      {
        title: 'Healthcare Infrastructure Gaps',
        titleAr: 'فجوات البنية التحتية الصحية',
        description: 'Many African countries face severe shortages in medical facilities, qualified personnel, and essential medicines.',
        descriptionAr: 'تواجه العديد من الدول الأفريقية نقصاً حاداً في المنشآت الطبية والموظفين المؤهلين والأدوية الأساسية.',
        solution: 'We establish and operate medical clinics, train local healthcare workers, provide essential medicines, and coordinate with international health partners to expand access to quality healthcare.',
        solutionAr: 'نؤسس ونشغل عيادات طبية، ندرب العاملين الصحيين المحليين، نوفر الأدوية الأساسية، ونتنسق مع شركاء الصحة الدوليين لتوسيع الوصول إلى الرعاية الصحية الجودة.',
      },
      {
        title: 'Food Insecurity & Malnutrition',
        titleAr: 'انعدام الأمن الغذائي وسوء التغذية',
        description: 'Climate variability, conflict, and poverty create severe food shortages affecting millions of people.',
        descriptionAr: 'تتسبب التغيرات المناخية والصراعات والفقر في نقص حاد في الغذاء يؤثر على ملايين الناس.',
        solution: 'JHCO implements comprehensive food security programs including emergency distribution, nutritional support, agricultural training, and livelihood initiatives to build resilience.',
        solutionAr: 'تنفذ الهيئة برامج أمن غذائي شاملة تشمل التوزيع الطارئ والدعم الغذائي والتدريب الزراعي ومبادرات سبل العيش لبناء المرونة.',
      },
      {
        title: 'Education Access & Quality',
        titleAr: 'الوصول إلى التعليم وجودته',
        description: 'Limited school infrastructure and teacher availability prevent millions of children from accessing education.',
        descriptionAr: 'تحد البنية التحتية المدرسية المحدودة وتوفر المعلمين من وصول ملايين الأطفال إلى التعليم.',
        solution: 'We provide scholarships, build learning centers, train teachers, and supply educational materials to expand access to quality education and empower the next generation.',
        solutionAr: 'نوفر المنح والمراكز التعليمية، ندرب المعلمين، ونوفر المواد التعليمية لتوسيع الوصول إلى التعليم الجودة وتمكين الجيل القادم.',
      },
      {
        title: 'Water & Sanitation Crisis',
        titleAr: 'أزمة المياه والصرف الصحي',
        description: 'Inadequate WASH infrastructure leads to disease outbreaks and preventable deaths.',
        descriptionAr: 'تؤدي البنية التحتية غير الكافية للمياه والصرف إلى تفشي الأمراض والوفيات التي يمكن الوقاية منها.',
        solution: 'We construct water wells, install sanitation facilities, and provide hygiene education to improve public health and prevent waterborne diseases.',
        solutionAr: 'نبني آبار مياه، ننشئ مرافق صرف صحي، ونوفر تثقيفاً صحياً لتحسين الصحة العامة والوقاية من الأمراض المائية.',
      },
    ],
    successStories: [
      {
        title: 'Somalia School Feeding Success',
        titleAr: 'نجاح برنامج الغذاء المدرسي في الصومال',
        description: 'Our school feeding program in Somalia now provides 3,500 daily meals to children, increasing enrollment by 40% and improving learning outcomes.',
        descriptionAr: 'يوفر برنامج الغذاء المدرسي بالهيئة في الصومال الآن 3,500 وجبة يومية للأطفال، مما زاد الالتحاق بنسبة 40% وحسّن نتائج التعلم.',
      },
      {
        title: 'Sudan Emergency Response',
        titleAr: 'الاستجابة الطارئة في السودان',
        description: 'During the recent crisis, JHCO deployed emergency teams within 48 hours, reaching 10,000 families with food, water, and medical assistance.',
        descriptionAr: 'خلال الأزمة الأخيرة، نشرت الهيئة فرق الطوارئ في غضون 48 ساعة، ووصلت إلى 10,000 أسرة بمساعدات الغذاء والمياه والطبية.',
      },
      {
        title: 'Egypt Medical Clinic Network',
        titleAr: 'شبكة العيادات الطبية في مصر',
        description: 'Our 12 medical clinics across Egypt have treated over 50,000 patients, providing free healthcare to communities that previously had no access.',
        descriptionAr: 'عالجت عيادتنا الطبية الـ 12 عبر مصر أكثر من 50,000 مريض، وفرنا رعاية صحية مجانية للمجتمعات التي لم تكن لديها وصول سابقاً.',
      },
    ],
  },
};
